// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/athAdmin/v1/athAdmin.proto

package Admin

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenericReply struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericReply) Reset()         { *m = GenericReply{} }
func (m *GenericReply) String() string { return proto.CompactTextString(m) }
func (*GenericReply) ProtoMessage()    {}
func (*GenericReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9899574d71e5cc4, []int{0}
}

func (m *GenericReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericReply.Unmarshal(m, b)
}
func (m *GenericReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericReply.Marshal(b, m, deterministic)
}
func (m *GenericReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericReply.Merge(m, src)
}
func (m *GenericReply) XXX_Size() int {
	return xxx_messageInfo_GenericReply.Size(m)
}
func (m *GenericReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericReply.DiscardUnknown(m)
}

var xxx_messageInfo_GenericReply proto.InternalMessageInfo

func (m *GenericReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *GenericReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GenericReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SignupAdminRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	CreatedBy            int32    `protobuf:"varint,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupAdminRequest) Reset()         { *m = SignupAdminRequest{} }
func (m *SignupAdminRequest) String() string { return proto.CompactTextString(m) }
func (*SignupAdminRequest) ProtoMessage()    {}
func (*SignupAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9899574d71e5cc4, []int{1}
}

func (m *SignupAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupAdminRequest.Unmarshal(m, b)
}
func (m *SignupAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupAdminRequest.Marshal(b, m, deterministic)
}
func (m *SignupAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupAdminRequest.Merge(m, src)
}
func (m *SignupAdminRequest) XXX_Size() int {
	return xxx_messageInfo_SignupAdminRequest.Size(m)
}
func (m *SignupAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupAdminRequest proto.InternalMessageInfo

func (m *SignupAdminRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SignupAdminRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SignupAdminRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupAdminRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignupAdminRequest) GetCreatedBy() int32 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

type LoginAdminRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAdminRequest) Reset()         { *m = LoginAdminRequest{} }
func (m *LoginAdminRequest) String() string { return proto.CompactTextString(m) }
func (*LoginAdminRequest) ProtoMessage()    {}
func (*LoginAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9899574d71e5cc4, []int{2}
}

func (m *LoginAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAdminRequest.Unmarshal(m, b)
}
func (m *LoginAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAdminRequest.Marshal(b, m, deterministic)
}
func (m *LoginAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAdminRequest.Merge(m, src)
}
func (m *LoginAdminRequest) XXX_Size() int {
	return xxx_messageInfo_LoginAdminRequest.Size(m)
}
func (m *LoginAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAdminRequest proto.InternalMessageInfo

func (m *LoginAdminRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginAdminRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginAdminReply struct {
	Data                 *LoginAdminReplyData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status               bool                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error                string               `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LoginAdminReply) Reset()         { *m = LoginAdminReply{} }
func (m *LoginAdminReply) String() string { return proto.CompactTextString(m) }
func (*LoginAdminReply) ProtoMessage()    {}
func (*LoginAdminReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9899574d71e5cc4, []int{3}
}

func (m *LoginAdminReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAdminReply.Unmarshal(m, b)
}
func (m *LoginAdminReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAdminReply.Marshal(b, m, deterministic)
}
func (m *LoginAdminReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAdminReply.Merge(m, src)
}
func (m *LoginAdminReply) XXX_Size() int {
	return xxx_messageInfo_LoginAdminReply.Size(m)
}
func (m *LoginAdminReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAdminReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAdminReply proto.InternalMessageInfo

func (m *LoginAdminReply) GetData() *LoginAdminReplyData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LoginAdminReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *LoginAdminReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginAdminReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type LoginAdminReplyData struct {
	AdminId              string   `protobuf:"bytes,1,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginAdminReplyData) Reset()         { *m = LoginAdminReplyData{} }
func (m *LoginAdminReplyData) String() string { return proto.CompactTextString(m) }
func (*LoginAdminReplyData) ProtoMessage()    {}
func (*LoginAdminReplyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9899574d71e5cc4, []int{4}
}

func (m *LoginAdminReplyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginAdminReplyData.Unmarshal(m, b)
}
func (m *LoginAdminReplyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginAdminReplyData.Marshal(b, m, deterministic)
}
func (m *LoginAdminReplyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginAdminReplyData.Merge(m, src)
}
func (m *LoginAdminReplyData) XXX_Size() int {
	return xxx_messageInfo_LoginAdminReplyData.Size(m)
}
func (m *LoginAdminReplyData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginAdminReplyData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginAdminReplyData proto.InternalMessageInfo

func (m *LoginAdminReplyData) GetAdminId() string {
	if m != nil {
		return m.AdminId
	}
	return ""
}

func init() {
	proto.RegisterType((*GenericReply)(nil), "Admin.GenericReply")
	proto.RegisterType((*SignupAdminRequest)(nil), "Admin.SignupAdminRequest")
	proto.RegisterType((*LoginAdminRequest)(nil), "Admin.LoginAdminRequest")
	proto.RegisterType((*LoginAdminReply)(nil), "Admin.LoginAdminReply")
	proto.RegisterType((*LoginAdminReplyData)(nil), "Admin.LoginAdminReplyData")
}

func init() { proto.RegisterFile("api/athAdmin/v1/athAdmin.proto", fileDescriptor_b9899574d71e5cc4) }

var fileDescriptor_b9899574d71e5cc4 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcd, 0x6e, 0xe2, 0x30,
	0x10, 0xc6, 0x90, 0x40, 0x32, 0xac, 0xb4, 0xda, 0x61, 0x85, 0x42, 0xf6, 0x47, 0x28, 0x27, 0x4e,
	0xb0, 0xcb, 0x3e, 0xc0, 0xb6, 0x55, 0xab, 0xaa, 0x52, 0xd5, 0x43, 0x2a, 0xf5, 0x8a, 0x0c, 0xb1,
	0x52, 0x4b, 0xc4, 0x4e, 0x6d, 0xa7, 0x15, 0x8f, 0xd0, 0x3e, 0x40, 0x9f, 0xb7, 0x8a, 0x13, 0x68,
	0x68, 0xe1, 0xe6, 0x6f, 0xe6, 0xf3, 0x37, 0x33, 0xdf, 0x0c, 0xfc, 0xa6, 0x39, 0x9f, 0x51, 0x73,
	0x7f, 0x9a, 0x64, 0x5c, 0xcc, 0x1e, 0xff, 0xee, 0xde, 0xd3, 0x5c, 0x49, 0x23, 0xd1, 0xb5, 0x20,
	0xfc, 0x99, 0x4a, 0x99, 0xae, 0xd9, 0xcc, 0xb2, 0x85, 0x90, 0x86, 0x1a, 0x2e, 0x85, 0xae, 0x48,
	0xd1, 0x1d, 0x7c, 0xb9, 0x64, 0x82, 0x29, 0xbe, 0x8a, 0x59, 0xbe, 0xde, 0xe0, 0x10, 0xba, 0xda,
	0x50, 0x53, 0xe8, 0x80, 0x8c, 0xc9, 0xc4, 0x8b, 0x6b, 0x84, 0x01, 0xf4, 0x32, 0xa6, 0x35, 0x4d,
	0x59, 0xd0, 0x1e, 0x93, 0x89, 0x1f, 0x6f, 0x21, 0x7e, 0x07, 0x97, 0x29, 0x25, 0x55, 0xd0, 0xb1,
	0xf1, 0x0a, 0x44, 0xaf, 0x04, 0xf0, 0x96, 0xa7, 0xa2, 0xc8, 0x6d, 0x17, 0x31, 0x7b, 0x28, 0x98,
	0x36, 0x88, 0xe0, 0x08, 0x9a, 0x31, 0x2b, 0xee, 0xc7, 0xf6, 0x8d, 0x3f, 0xc0, 0x2f, 0x34, 0x53,
	0x0b, 0x9b, 0xa8, 0xc4, 0xbd, 0x32, 0x70, 0x53, 0x26, 0x4b, 0xf5, 0x8c, 0xf2, 0xf5, 0x4e, 0xbd,
	0x04, 0x18, 0x82, 0x97, 0x53, 0xad, 0x9f, 0xa4, 0x4a, 0x02, 0xa7, 0xfa, 0xb1, 0xc5, 0xf8, 0x0b,
	0x60, 0xa5, 0x18, 0x35, 0x2c, 0x59, 0x2c, 0x37, 0x81, 0x3b, 0x26, 0x13, 0x37, 0xf6, 0xeb, 0xc8,
	0xd9, 0x26, 0xba, 0x80, 0x6f, 0xd7, 0x32, 0xe5, 0x62, 0xaf, 0xad, 0x5d, 0x15, 0x72, 0xac, 0x4a,
	0x67, 0xbf, 0x4a, 0xf4, 0x4c, 0xe0, 0x6b, 0x53, 0xa7, 0xf4, 0x6e, 0x0a, 0x4e, 0x42, 0x0d, 0xb5,
	0x22, 0xfd, 0x79, 0x38, 0xad, 0x96, 0xf1, 0x81, 0x75, 0x4e, 0x0d, 0x8d, 0x2d, 0xaf, 0xe1, 0x75,
	0xfb, 0x98, 0xd7, 0x9d, 0x23, 0x5e, 0x3b, 0x4d, 0xaf, 0xff, 0xc0, 0xe0, 0x40, 0x11, 0x1c, 0x81,
	0x47, 0xcb, 0xc8, 0x82, 0x27, 0xf5, 0x5c, 0x3d, 0x8b, 0xaf, 0x92, 0xf9, 0x0b, 0x81, 0xea, 0x3a,
	0xf0, 0x04, 0xe0, 0xfd, 0x2f, 0x06, 0x07, 0x7a, 0xb6, 0x0e, 0x85, 0xc3, 0xc3, 0xd3, 0x44, 0x2d,
	0xfc, 0x0f, 0xfd, 0xc6, 0xa2, 0x71, 0x54, 0x13, 0x3f, 0x2f, 0x3f, 0x1c, 0xd4, 0xa9, 0xe6, 0xc1,
	0x45, 0xad, 0x65, 0xd7, 0x5e, 0xe2, 0xbf, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x38, 0x79, 0x10,
	0xb8, 0xd0, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminClient interface {
	LoginAdmin(ctx context.Context, in *LoginAdminRequest, opts ...grpc.CallOption) (*LoginAdminReply, error)
	SignupAdmin(ctx context.Context, in *SignupAdminRequest, opts ...grpc.CallOption) (*GenericReply, error)
}

type adminClient struct {
	cc *grpc.ClientConn
}

func NewAdminClient(cc *grpc.ClientConn) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) LoginAdmin(ctx context.Context, in *LoginAdminRequest, opts ...grpc.CallOption) (*LoginAdminReply, error) {
	out := new(LoginAdminReply)
	err := c.cc.Invoke(ctx, "/Admin.Admin/LoginAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) SignupAdmin(ctx context.Context, in *SignupAdminRequest, opts ...grpc.CallOption) (*GenericReply, error) {
	out := new(GenericReply)
	err := c.cc.Invoke(ctx, "/Admin.Admin/SignupAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
type AdminServer interface {
	LoginAdmin(context.Context, *LoginAdminRequest) (*LoginAdminReply, error)
	SignupAdmin(context.Context, *SignupAdminRequest) (*GenericReply, error)
}

// UnimplementedAdminServer can be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (*UnimplementedAdminServer) LoginAdmin(ctx context.Context, req *LoginAdminRequest) (*LoginAdminReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginAdmin not implemented")
}
func (*UnimplementedAdminServer) SignupAdmin(ctx context.Context, req *SignupAdminRequest) (*GenericReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignupAdmin not implemented")
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_LoginAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).LoginAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Admin.Admin/LoginAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).LoginAdmin(ctx, req.(*LoginAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_SignupAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).SignupAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Admin.Admin/SignupAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).SignupAdmin(ctx, req.(*SignupAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Admin.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginAdmin",
			Handler:    _Admin_LoginAdmin_Handler,
		},
		{
			MethodName: "SignupAdmin",
			Handler:    _Admin_SignupAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/athAdmin/v1/athAdmin.proto",
}
