// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/athFacility/v1/athFacility.proto

package Facility

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WeekDataEdit struct {
	Weekdays             map[string]float32 `protobuf:"bytes,1,rep,name=weekdays,proto3" json:"weekdays,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	Weekends             map[string]float32 `protobuf:"bytes,2,rep,name=weekends,proto3" json:"weekends,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WeekDataEdit) Reset()         { *m = WeekDataEdit{} }
func (m *WeekDataEdit) String() string { return proto.CompactTextString(m) }
func (*WeekDataEdit) ProtoMessage()    {}
func (*WeekDataEdit) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a666a82eda00140, []int{0}
}

func (m *WeekDataEdit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeekDataEdit.Unmarshal(m, b)
}
func (m *WeekDataEdit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeekDataEdit.Marshal(b, m, deterministic)
}
func (m *WeekDataEdit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeekDataEdit.Merge(m, src)
}
func (m *WeekDataEdit) XXX_Size() int {
	return xxx_messageInfo_WeekDataEdit.Size(m)
}
func (m *WeekDataEdit) XXX_DiscardUnknown() {
	xxx_messageInfo_WeekDataEdit.DiscardUnknown(m)
}

var xxx_messageInfo_WeekDataEdit proto.InternalMessageInfo

func (m *WeekDataEdit) GetWeekdays() map[string]float32 {
	if m != nil {
		return m.Weekdays
	}
	return nil
}

func (m *WeekDataEdit) GetWeekends() map[string]float32 {
	if m != nil {
		return m.Weekends
	}
	return nil
}

type WeekData struct {
	Weekdays             map[string]*Weekslots `protobuf:"bytes,1,rep,name=weekdays,proto3" json:"weekdays,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Weekends             map[string]*Weekslots `protobuf:"bytes,2,rep,name=weekends,proto3" json:"weekends,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *WeekData) Reset()         { *m = WeekData{} }
func (m *WeekData) String() string { return proto.CompactTextString(m) }
func (*WeekData) ProtoMessage()    {}
func (*WeekData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a666a82eda00140, []int{1}
}

func (m *WeekData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeekData.Unmarshal(m, b)
}
func (m *WeekData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeekData.Marshal(b, m, deterministic)
}
func (m *WeekData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeekData.Merge(m, src)
}
func (m *WeekData) XXX_Size() int {
	return xxx_messageInfo_WeekData.Size(m)
}
func (m *WeekData) XXX_DiscardUnknown() {
	xxx_messageInfo_WeekData.DiscardUnknown(m)
}

var xxx_messageInfo_WeekData proto.InternalMessageInfo

func (m *WeekData) GetWeekdays() map[string]*Weekslots {
	if m != nil {
		return m.Weekdays
	}
	return nil
}

func (m *WeekData) GetWeekends() map[string]*Weekslots {
	if m != nil {
		return m.Weekends
	}
	return nil
}

type Weekslots struct {
	Price                float32  `protobuf:"fixed32,1,opt,name=price,proto3" json:"price,omitempty"`
	Slot                 string   `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Weekslots) Reset()         { *m = Weekslots{} }
func (m *Weekslots) String() string { return proto.CompactTextString(m) }
func (*Weekslots) ProtoMessage()    {}
func (*Weekslots) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a666a82eda00140, []int{2}
}

func (m *Weekslots) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Weekslots.Unmarshal(m, b)
}
func (m *Weekslots) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Weekslots.Marshal(b, m, deterministic)
}
func (m *Weekslots) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Weekslots.Merge(m, src)
}
func (m *Weekslots) XXX_Size() int {
	return xxx_messageInfo_Weekslots.Size(m)
}
func (m *Weekslots) XXX_DiscardUnknown() {
	xxx_messageInfo_Weekslots.DiscardUnknown(m)
}

var xxx_messageInfo_Weekslots proto.InternalMessageInfo

func (m *Weekslots) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Weekslots) GetSlot() string {
	if m != nil {
		return m.Slot
	}
	return ""
}

type GenericReply struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericReply) Reset()         { *m = GenericReply{} }
func (m *GenericReply) String() string { return proto.CompactTextString(m) }
func (*GenericReply) ProtoMessage()    {}
func (*GenericReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a666a82eda00140, []int{3}
}

func (m *GenericReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericReply.Unmarshal(m, b)
}
func (m *GenericReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericReply.Marshal(b, m, deterministic)
}
func (m *GenericReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericReply.Merge(m, src)
}
func (m *GenericReply) XXX_Size() int {
	return xxx_messageInfo_GenericReply.Size(m)
}
func (m *GenericReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericReply.DiscardUnknown(m)
}

var xxx_messageInfo_GenericReply proto.InternalMessageInfo

func (m *GenericReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *GenericReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GenericReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type BookFacilityRequest struct {
	CreatedBy            int32    `protobuf:"varint,1,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	BookingDate          string   `protobuf:"bytes,2,opt,name=booking_date,json=bookingDate,proto3" json:"booking_date,omitempty"`
	BaseTotalAmount      float32  `protobuf:"fixed32,3,opt,name=base_total_amount,json=baseTotalAmount,proto3" json:"base_total_amount,omitempty"`
	DiscountAmount       float32  `protobuf:"fixed32,4,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	BookingAmount        float32  `protobuf:"fixed32,5,opt,name=booking_amount,json=bookingAmount,proto3" json:"booking_amount,omitempty"`
	FacilitySlotId       int32    `protobuf:"varint,6,opt,name=facility_slot_id,json=facilitySlotId,proto3" json:"facility_slot_id,omitempty"`
	SlotDays             string   `protobuf:"bytes,7,opt,name=slot_days,json=slotDays,proto3" json:"slot_days,omitempty"`
	SlotFromDate         string   `protobuf:"bytes,8,opt,name=slot_from_date,json=slotFromDate,proto3" json:"slot_from_date,omitempty"`
	SlotToDate           string   `protobuf:"bytes,9,opt,name=slot_to_date,json=slotToDate,proto3" json:"slot_to_date,omitempty"`
	SlotBookingPrice     float32  `protobuf:"fixed32,10,opt,name=slot_booking_price,json=slotBookingPrice,proto3" json:"slot_booking_price,omitempty"`
	BookingFee           float32  `protobuf:"fixed32,11,opt,name=booking_fee,json=bookingFee,proto3" json:"booking_fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookFacilityRequest) Reset()         { *m = BookFacilityRequest{} }
func (m *BookFacilityRequest) String() string { return proto.CompactTextString(m) }
func (*BookFacilityRequest) ProtoMessage()    {}
func (*BookFacilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a666a82eda00140, []int{4}
}

func (m *BookFacilityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookFacilityRequest.Unmarshal(m, b)
}
func (m *BookFacilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookFacilityRequest.Marshal(b, m, deterministic)
}
func (m *BookFacilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookFacilityRequest.Merge(m, src)
}
func (m *BookFacilityRequest) XXX_Size() int {
	return xxx_messageInfo_BookFacilityRequest.Size(m)
}
func (m *BookFacilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookFacilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookFacilityRequest proto.InternalMessageInfo

func (m *BookFacilityRequest) GetCreatedBy() int32 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *BookFacilityRequest) GetBookingDate() string {
	if m != nil {
		return m.BookingDate
	}
	return ""
}

func (m *BookFacilityRequest) GetBaseTotalAmount() float32 {
	if m != nil {
		return m.BaseTotalAmount
	}
	return 0
}

func (m *BookFacilityRequest) GetDiscountAmount() float32 {
	if m != nil {
		return m.DiscountAmount
	}
	return 0
}

func (m *BookFacilityRequest) GetBookingAmount() float32 {
	if m != nil {
		return m.BookingAmount
	}
	return 0
}

func (m *BookFacilityRequest) GetFacilitySlotId() int32 {
	if m != nil {
		return m.FacilitySlotId
	}
	return 0
}

func (m *BookFacilityRequest) GetSlotDays() string {
	if m != nil {
		return m.SlotDays
	}
	return ""
}

func (m *BookFacilityRequest) GetSlotFromDate() string {
	if m != nil {
		return m.SlotFromDate
	}
	return ""
}

func (m *BookFacilityRequest) GetSlotToDate() string {
	if m != nil {
		return m.SlotToDate
	}
	return ""
}

func (m *BookFacilityRequest) GetSlotBookingPrice() float32 {
	if m != nil {
		return m.SlotBookingPrice
	}
	return 0
}

func (m *BookFacilityRequest) GetBookingFee() float32 {
	if m != nil {
		return m.BookingFee
	}
	return 0
}

type BookFacilityReply struct {
	Data                 *BookFacilityReplyData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status               bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error                string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BookFacilityReply) Reset()         { *m = BookFacilityReply{} }
func (m *BookFacilityReply) String() string { return proto.CompactTextString(m) }
func (*BookFacilityReply) ProtoMessage()    {}
func (*BookFacilityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a666a82eda00140, []int{5}
}

func (m *BookFacilityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookFacilityReply.Unmarshal(m, b)
}
func (m *BookFacilityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookFacilityReply.Marshal(b, m, deterministic)
}
func (m *BookFacilityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookFacilityReply.Merge(m, src)
}
func (m *BookFacilityReply) XXX_Size() int {
	return xxx_messageInfo_BookFacilityReply.Size(m)
}
func (m *BookFacilityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BookFacilityReply.DiscardUnknown(m)
}

var xxx_messageInfo_BookFacilityReply proto.InternalMessageInfo

func (m *BookFacilityReply) GetData() *BookFacilityReplyData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BookFacilityReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *BookFacilityReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BookFacilityReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type BookFacilityReplyData struct {
	BookingId            int32    `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	BookingNo            string   `protobuf:"bytes,2,opt,name=booking_no,json=bookingNo,proto3" json:"booking_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookFacilityReplyData) Reset()         { *m = BookFacilityReplyData{} }
func (m *BookFacilityReplyData) String() string { return proto.CompactTextString(m) }
func (*BookFacilityReplyData) ProtoMessage()    {}
func (*BookFacilityReplyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a666a82eda00140, []int{6}
}

func (m *BookFacilityReplyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookFacilityReplyData.Unmarshal(m, b)
}
func (m *BookFacilityReplyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookFacilityReplyData.Marshal(b, m, deterministic)
}
func (m *BookFacilityReplyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookFacilityReplyData.Merge(m, src)
}
func (m *BookFacilityReplyData) XXX_Size() int {
	return xxx_messageInfo_BookFacilityReplyData.Size(m)
}
func (m *BookFacilityReplyData) XXX_DiscardUnknown() {
	xxx_messageInfo_BookFacilityReplyData.DiscardUnknown(m)
}

var xxx_messageInfo_BookFacilityReplyData proto.InternalMessageInfo

func (m *BookFacilityReplyData) GetBookingId() int32 {
	if m != nil {
		return m.BookingId
	}
	return 0
}

func (m *BookFacilityReplyData) GetBookingNo() string {
	if m != nil {
		return m.BookingNo
	}
	return ""
}

type CreateFacilityRequest struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VenueId              int32     `protobuf:"varint,2,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	BasePrice            float32   `protobuf:"fixed32,3,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	TimeSlot             int32     `protobuf:"varint,4,opt,name=time_slot,json=timeSlot,proto3" json:"time_slot,omitempty"`
	SportCategories      string    `protobuf:"bytes,5,opt,name=sport_categories,json=sportCategories,proto3" json:"sport_categories,omitempty"`
	CreatedBy            int32     `protobuf:"varint,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	WeekData             *WeekData `protobuf:"bytes,7,opt,name=week_data,json=weekData,proto3" json:"week_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateFacilityRequest) Reset()         { *m = CreateFacilityRequest{} }
func (m *CreateFacilityRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFacilityRequest) ProtoMessage()    {}
func (*CreateFacilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a666a82eda00140, []int{7}
}

func (m *CreateFacilityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFacilityRequest.Unmarshal(m, b)
}
func (m *CreateFacilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFacilityRequest.Marshal(b, m, deterministic)
}
func (m *CreateFacilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFacilityRequest.Merge(m, src)
}
func (m *CreateFacilityRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFacilityRequest.Size(m)
}
func (m *CreateFacilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFacilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFacilityRequest proto.InternalMessageInfo

func (m *CreateFacilityRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateFacilityRequest) GetVenueId() int32 {
	if m != nil {
		return m.VenueId
	}
	return 0
}

func (m *CreateFacilityRequest) GetBasePrice() float32 {
	if m != nil {
		return m.BasePrice
	}
	return 0
}

func (m *CreateFacilityRequest) GetTimeSlot() int32 {
	if m != nil {
		return m.TimeSlot
	}
	return 0
}

func (m *CreateFacilityRequest) GetSportCategories() string {
	if m != nil {
		return m.SportCategories
	}
	return ""
}

func (m *CreateFacilityRequest) GetCreatedBy() int32 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *CreateFacilityRequest) GetWeekData() *WeekData {
	if m != nil {
		return m.WeekData
	}
	return nil
}

type EditFacilityRequest struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BasePrice            float32        `protobuf:"fixed32,2,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	SportCategories      string         `protobuf:"bytes,3,opt,name=sport_categories,json=sportCategories,proto3" json:"sport_categories,omitempty"`
	UpdatedBy            int32          `protobuf:"varint,4,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	WeekData             *WeekDataEdit  `protobuf:"bytes,5,opt,name=week_data,json=weekData,proto3" json:"week_data,omitempty"`
	FacilityId           int32          `protobuf:"varint,6,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	CustomRates          []*CustomRates `protobuf:"bytes,7,rep,name=custom_rates,json=customRates,proto3" json:"custom_rates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *EditFacilityRequest) Reset()         { *m = EditFacilityRequest{} }
func (m *EditFacilityRequest) String() string { return proto.CompactTextString(m) }
func (*EditFacilityRequest) ProtoMessage()    {}
func (*EditFacilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a666a82eda00140, []int{8}
}

func (m *EditFacilityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditFacilityRequest.Unmarshal(m, b)
}
func (m *EditFacilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditFacilityRequest.Marshal(b, m, deterministic)
}
func (m *EditFacilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditFacilityRequest.Merge(m, src)
}
func (m *EditFacilityRequest) XXX_Size() int {
	return xxx_messageInfo_EditFacilityRequest.Size(m)
}
func (m *EditFacilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditFacilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditFacilityRequest proto.InternalMessageInfo

func (m *EditFacilityRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditFacilityRequest) GetBasePrice() float32 {
	if m != nil {
		return m.BasePrice
	}
	return 0
}

func (m *EditFacilityRequest) GetSportCategories() string {
	if m != nil {
		return m.SportCategories
	}
	return ""
}

func (m *EditFacilityRequest) GetUpdatedBy() int32 {
	if m != nil {
		return m.UpdatedBy
	}
	return 0
}

func (m *EditFacilityRequest) GetWeekData() *WeekDataEdit {
	if m != nil {
		return m.WeekData
	}
	return nil
}

func (m *EditFacilityRequest) GetFacilityId() int32 {
	if m != nil {
		return m.FacilityId
	}
	return 0
}

func (m *EditFacilityRequest) GetCustomRates() []*CustomRates {
	if m != nil {
		return m.CustomRates
	}
	return nil
}

type CustomRates struct {
	FacilitySlotId       int32    `protobuf:"varint,1,opt,name=facility_slot_id,json=facilitySlotId,proto3" json:"facility_slot_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FacilityId           int32    `protobuf:"varint,3,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	Date                 string   `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	SlotPrice            float32  `protobuf:"fixed32,5,opt,name=slot_price,json=slotPrice,proto3" json:"slot_price,omitempty"`
	Available            bool     `protobuf:"varint,6,opt,name=available,proto3" json:"available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomRates) Reset()         { *m = CustomRates{} }
func (m *CustomRates) String() string { return proto.CompactTextString(m) }
func (*CustomRates) ProtoMessage()    {}
func (*CustomRates) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a666a82eda00140, []int{9}
}

func (m *CustomRates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomRates.Unmarshal(m, b)
}
func (m *CustomRates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomRates.Marshal(b, m, deterministic)
}
func (m *CustomRates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomRates.Merge(m, src)
}
func (m *CustomRates) XXX_Size() int {
	return xxx_messageInfo_CustomRates.Size(m)
}
func (m *CustomRates) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomRates.DiscardUnknown(m)
}

var xxx_messageInfo_CustomRates proto.InternalMessageInfo

func (m *CustomRates) GetFacilitySlotId() int32 {
	if m != nil {
		return m.FacilitySlotId
	}
	return 0
}

func (m *CustomRates) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CustomRates) GetFacilityId() int32 {
	if m != nil {
		return m.FacilityId
	}
	return 0
}

func (m *CustomRates) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *CustomRates) GetSlotPrice() float32 {
	if m != nil {
		return m.SlotPrice
	}
	return 0
}

func (m *CustomRates) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

type CreateFacilityReply struct {
	Data                 *CreateFacilityReplyData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status               bool                     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string                   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error                string                   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CreateFacilityReply) Reset()         { *m = CreateFacilityReply{} }
func (m *CreateFacilityReply) String() string { return proto.CompactTextString(m) }
func (*CreateFacilityReply) ProtoMessage()    {}
func (*CreateFacilityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a666a82eda00140, []int{10}
}

func (m *CreateFacilityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFacilityReply.Unmarshal(m, b)
}
func (m *CreateFacilityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFacilityReply.Marshal(b, m, deterministic)
}
func (m *CreateFacilityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFacilityReply.Merge(m, src)
}
func (m *CreateFacilityReply) XXX_Size() int {
	return xxx_messageInfo_CreateFacilityReply.Size(m)
}
func (m *CreateFacilityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFacilityReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFacilityReply proto.InternalMessageInfo

func (m *CreateFacilityReply) GetData() *CreateFacilityReplyData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateFacilityReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *CreateFacilityReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateFacilityReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateFacilityReplyData struct {
	FacilityId           int32    `protobuf:"varint,1,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFacilityReplyData) Reset()         { *m = CreateFacilityReplyData{} }
func (m *CreateFacilityReplyData) String() string { return proto.CompactTextString(m) }
func (*CreateFacilityReplyData) ProtoMessage()    {}
func (*CreateFacilityReplyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a666a82eda00140, []int{11}
}

func (m *CreateFacilityReplyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFacilityReplyData.Unmarshal(m, b)
}
func (m *CreateFacilityReplyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFacilityReplyData.Marshal(b, m, deterministic)
}
func (m *CreateFacilityReplyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFacilityReplyData.Merge(m, src)
}
func (m *CreateFacilityReplyData) XXX_Size() int {
	return xxx_messageInfo_CreateFacilityReplyData.Size(m)
}
func (m *CreateFacilityReplyData) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFacilityReplyData.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFacilityReplyData proto.InternalMessageInfo

func (m *CreateFacilityReplyData) GetFacilityId() int32 {
	if m != nil {
		return m.FacilityId
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a666a82eda00140, []int{12}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*WeekDataEdit)(nil), "Facility.WeekDataEdit")
	proto.RegisterMapType((map[string]float32)(nil), "Facility.WeekDataEdit.WeekdaysEntry")
	proto.RegisterMapType((map[string]float32)(nil), "Facility.WeekDataEdit.WeekendsEntry")
	proto.RegisterType((*WeekData)(nil), "Facility.WeekData")
	proto.RegisterMapType((map[string]*Weekslots)(nil), "Facility.WeekData.WeekdaysEntry")
	proto.RegisterMapType((map[string]*Weekslots)(nil), "Facility.WeekData.WeekendsEntry")
	proto.RegisterType((*Weekslots)(nil), "Facility.Weekslots")
	proto.RegisterType((*GenericReply)(nil), "Facility.GenericReply")
	proto.RegisterType((*BookFacilityRequest)(nil), "Facility.BookFacilityRequest")
	proto.RegisterType((*BookFacilityReply)(nil), "Facility.BookFacilityReply")
	proto.RegisterType((*BookFacilityReplyData)(nil), "Facility.BookFacilityReplyData")
	proto.RegisterType((*CreateFacilityRequest)(nil), "Facility.CreateFacilityRequest")
	proto.RegisterType((*EditFacilityRequest)(nil), "Facility.EditFacilityRequest")
	proto.RegisterType((*CustomRates)(nil), "Facility.CustomRates")
	proto.RegisterType((*CreateFacilityReply)(nil), "Facility.CreateFacilityReply")
	proto.RegisterType((*CreateFacilityReplyData)(nil), "Facility.CreateFacilityReplyData")
	proto.RegisterType((*Empty)(nil), "Facility.Empty")
}

func init() {
	proto.RegisterFile("api/athFacility/v1/athFacility.proto", fileDescriptor_8a666a82eda00140)
}

var fileDescriptor_8a666a82eda00140 = []byte{
	// 1005 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xcd, 0x8e, 0x1b, 0x45,
	0x10, 0xd6, 0x8c, 0x7f, 0xa7, 0xec, 0x38, 0x4e, 0x6f, 0x36, 0x19, 0xbc, 0x89, 0xd6, 0x19, 0x2d,
	0x62, 0x83, 0x50, 0x56, 0x6c, 0x14, 0x29, 0x0a, 0x39, 0xc0, 0xfe, 0xa1, 0xbd, 0xa0, 0xd5, 0x10,
	0xe0, 0x38, 0x6a, 0x7b, 0x7a, 0xcd, 0xc8, 0xe3, 0x69, 0x33, 0xd3, 0x5e, 0xe4, 0x2b, 0x67, 0x0e,
	0x48, 0xf0, 0x04, 0x1c, 0xb9, 0xf1, 0x04, 0x48, 0xbc, 0x02, 0xaf, 0xc0, 0x6b, 0x20, 0xa1, 0xaa,
	0x99, 0xb6, 0xdb, 0x63, 0x3b, 0x4b, 0x0e, 0xdc, 0xba, 0xbe, 0xaa, 0xae, 0xea, 0xaf, 0xfa, 0xab,
	0x9e, 0x81, 0x03, 0x3e, 0x8d, 0x8e, 0xb8, 0xfa, 0xf6, 0x82, 0x0f, 0xa3, 0x38, 0x52, 0xf3, 0xa3,
	0x9b, 0x8f, 0x4d, 0xf3, 0xd9, 0x34, 0x95, 0x4a, 0xb2, 0xa6, 0xb6, 0x7b, 0x8f, 0x46, 0x52, 0x8e,
	0x62, 0x71, 0x44, 0xdb, 0x92, 0x44, 0x2a, 0xae, 0x22, 0x99, 0x64, 0x79, 0x9c, 0xf7, 0xa3, 0x0d,
	0xed, 0x6f, 0x84, 0x18, 0x9f, 0x71, 0xc5, 0xcf, 0xc3, 0x48, 0xb1, 0x4f, 0xa1, 0xf9, 0xbd, 0x10,
	0xe3, 0x90, 0xcf, 0x33, 0xd7, 0xea, 0x57, 0x0e, 0x5b, 0xc7, 0x07, 0xcf, 0x16, 0xb9, 0xcd, 0x48,
	0x32, 0x30, 0xec, 0x3c, 0x51, 0xe9, 0xdc, 0x5f, 0xec, 0xd2, 0x19, 0x44, 0x12, 0x66, 0xae, 0x7d,
	0x6b, 0x06, 0x0c, 0x33, 0x32, 0xa0, 0xd9, 0xfb, 0x04, 0xee, 0xac, 0x24, 0x67, 0x5d, 0xa8, 0x8c,
	0xc5, 0xdc, 0xb5, 0xfa, 0xd6, 0xa1, 0xe3, 0xe3, 0x92, 0xdd, 0x87, 0xda, 0x0d, 0x8f, 0x67, 0xc2,
	0xb5, 0xfb, 0xd6, 0xa1, 0xed, 0xe7, 0xc6, 0x2b, 0xfb, 0xa5, 0xa5, 0x37, 0x2f, 0xf2, 0xbe, 0xcb,
	0x66, 0xef, 0x37, 0x1b, 0x9a, 0xfa, 0x88, 0xec, 0xf5, 0x5a, 0x2b, 0xfa, 0xeb, 0x44, 0xb6, 0xb6,
	0xe1, 0xf5, 0x5a, 0x1b, 0xb6, 0xed, 0xde, 0xd4, 0x82, 0xab, 0xdb, 0x5b, 0xf0, 0xd4, 0x64, 0xd1,
	0x3a, 0xde, 0x59, 0xcd, 0x9e, 0xc5, 0x52, 0x65, 0x66, 0x5f, 0xae, 0x6e, 0xef, 0xcb, 0xbb, 0x65,
	0xf4, 0x5e, 0x80, 0xb3, 0xc0, 0xb1, 0xa7, 0xd3, 0x34, 0x1a, 0x0a, 0xca, 0x67, 0xfb, 0xb9, 0xc1,
	0x18, 0x54, 0xd1, 0x4d, 0x09, 0x1d, 0x9f, 0xd6, 0xde, 0xd7, 0xd0, 0xfe, 0x5c, 0x24, 0x22, 0x8d,
	0x86, 0xbe, 0x98, 0xc6, 0x73, 0xf6, 0x00, 0xea, 0x99, 0xe2, 0x6a, 0x96, 0xd1, 0xd6, 0xa6, 0x5f,
	0x58, 0xcc, 0x85, 0xc6, 0x44, 0x64, 0x19, 0x1f, 0x89, 0x62, 0xbb, 0x36, 0xb1, 0x96, 0x48, 0x53,
	0x99, 0xba, 0x15, 0xc2, 0x73, 0xc3, 0xfb, 0xbd, 0x02, 0x3b, 0x27, 0x52, 0x8e, 0xf5, 0xa1, 0x7d,
	0xf1, 0xdd, 0x4c, 0x64, 0x8a, 0x3d, 0x06, 0x18, 0xa6, 0x82, 0x2b, 0x11, 0x06, 0x83, 0x9c, 0x6e,
	0xcd, 0x77, 0x0a, 0xe4, 0x64, 0xce, 0x9e, 0x40, 0x7b, 0x20, 0xe5, 0x38, 0x4a, 0x46, 0x41, 0xc8,
	0x95, 0xae, 0xd5, 0x2a, 0xb0, 0x33, 0xae, 0x04, 0xfb, 0x10, 0xee, 0x0d, 0x78, 0x26, 0x02, 0x25,
	0x15, 0x8f, 0x03, 0x3e, 0x91, 0xb3, 0x44, 0x51, 0x6d, 0xdb, 0xbf, 0x8b, 0x8e, 0x37, 0x88, 0x7f,
	0x46, 0x30, 0xfb, 0x00, 0xee, 0x86, 0x51, 0x36, 0xc4, 0xb5, 0x8e, 0xac, 0x52, 0x64, 0x47, 0xc3,
	0x45, 0xe0, 0xfb, 0xd0, 0xd1, 0x75, 0x8b, 0xb8, 0x1a, 0xc5, 0xdd, 0x29, 0xd0, 0x22, 0xec, 0x10,
	0xba, 0xd7, 0x05, 0xa1, 0x00, 0xdb, 0x17, 0x44, 0xa1, 0x5b, 0x27, 0x0e, 0x1d, 0x8d, 0x7f, 0x19,
	0x4b, 0x75, 0x19, 0xb2, 0x3d, 0x70, 0x28, 0x80, 0xf4, 0xda, 0x20, 0x16, 0x4d, 0x04, 0xce, 0x50,
	0x8d, 0x07, 0xd0, 0x21, 0xe7, 0x75, 0x2a, 0x27, 0x39, 0xcf, 0x26, 0x45, 0xb4, 0x11, 0xbd, 0x48,
	0xe5, 0x84, 0x88, 0xf6, 0x81, 0xec, 0x40, 0xc9, 0x3c, 0xc6, 0xa1, 0x18, 0x40, 0xec, 0x8d, 0xa4,
	0x88, 0x8f, 0x80, 0x51, 0x84, 0x3e, 0x7a, 0x7e, 0xe7, 0x40, 0x27, 0xef, 0xa2, 0xe7, 0x24, 0x77,
	0x5c, 0xd1, 0xf5, 0xef, 0x83, 0xee, 0x63, 0x70, 0x2d, 0x84, 0xdb, 0xa2, 0x30, 0x28, 0xa0, 0x0b,
	0x21, 0xbc, 0x9f, 0x2c, 0xb8, 0xb7, 0x7a, 0x67, 0xa8, 0x88, 0xe7, 0x50, 0x0d, 0xb9, 0xe2, 0x74,
	0x57, 0xad, 0xe3, 0xfd, 0xa5, 0x0c, 0xd7, 0x42, 0x71, 0x86, 0x7c, 0x0a, 0x36, 0x64, 0x64, 0x6f,
	0x93, 0x51, 0x65, 0x8b, 0x8c, 0xaa, 0xa6, 0x8c, 0xbe, 0x82, 0xdd, 0x8d, 0x65, 0x50, 0x47, 0x9a,
	0x4c, 0x14, 0x6a, 0x1d, 0x15, 0xc8, 0x65, 0x68, 0xba, 0x13, 0x59, 0xa8, 0x48, 0xbb, 0xbf, 0x90,
	0xde, 0x3f, 0x16, 0xec, 0x9e, 0x92, 0xe8, 0xca, 0xfa, 0x64, 0x50, 0x4d, 0xf8, 0x44, 0x14, 0x83,
	0x48, 0x6b, 0xf6, 0x1e, 0x34, 0x6f, 0x44, 0x32, 0x13, 0x58, 0xc9, 0xa6, 0x4a, 0x0d, 0xb2, 0x8b,
	0x3a, 0x28, 0xc6, 0xbc, 0xf3, 0xb9, 0x0a, 0x1d, 0x44, 0xf2, 0x96, 0xef, 0x81, 0xa3, 0xa2, 0x89,
	0x20, 0xad, 0x10, 0xb1, 0x9a, 0xdf, 0x44, 0x00, 0x45, 0xc2, 0x9e, 0x42, 0x37, 0x9b, 0xca, 0x54,
	0x05, 0x43, 0xae, 0xc4, 0x48, 0xa6, 0x91, 0xc8, 0x48, 0x75, 0x8e, 0x7f, 0x97, 0xf0, 0xd3, 0x05,
	0x5c, 0x9a, 0x9a, 0x7a, 0x79, 0x6a, 0x8e, 0xc0, 0xc1, 0xb7, 0x2a, 0xa0, 0x7b, 0x6a, 0xd0, 0x3d,
	0xb1, 0xf5, 0xe7, 0x2d, 0x7f, 0xd0, 0x70, 0xe5, 0xfd, 0x6a, 0xc3, 0x0e, 0x3e, 0xfa, 0xff, 0x85,
	0xfd, 0x2a, 0x45, 0xbb, 0x4c, 0x71, 0x13, 0x8b, 0xca, 0x56, 0x16, 0xb3, 0x69, 0xa8, 0x59, 0xe4,
	0xed, 0x70, 0x0a, 0xe4, 0x04, 0x85, 0x66, 0xb0, 0xa8, 0x11, 0x8b, 0x07, 0x9b, 0xbf, 0x55, 0x4b,
	0x26, 0x28, 0xea, 0xc5, 0x44, 0x2e, 0x86, 0x11, 0x34, 0x74, 0x19, 0xb2, 0x97, 0xd0, 0x1e, 0xce,
	0x32, 0x25, 0x27, 0x41, 0xca, 0x95, 0xc0, 0x59, 0xc4, 0xd7, 0x7f, 0x77, 0x99, 0xf8, 0x94, 0xbc,
	0x3e, 0x3a, 0xfd, 0xd6, 0x70, 0x69, 0x78, 0x7f, 0x5a, 0xd0, 0x32, 0x9c, 0x1b, 0x87, 0xdf, 0xda,
	0x38, 0xfc, 0x0f, 0xa1, 0x31, 0xcb, 0x44, 0xba, 0xd4, 0x4b, 0x1d, 0xcd, 0xcb, 0xb0, 0x7c, 0xda,
	0xca, 0xda, 0x69, 0x19, 0x0d, 0x9b, 0x28, 0x86, 0x80, 0xd6, 0xd8, 0x36, 0x2a, 0x97, 0x5f, 0x40,
	0xfe, 0x2e, 0xd1, 0xe3, 0x92, 0x5f, 0xc0, 0x23, 0x70, 0xf8, 0x0d, 0x8f, 0x62, 0x3e, 0x88, 0x05,
	0xf1, 0x6f, 0xfa, 0x4b, 0xc0, 0xfb, 0xc5, 0x82, 0x9d, 0xb2, 0xd2, 0x71, 0xaa, 0x5f, 0xac, 0x4c,
	0xf5, 0x13, 0xa3, 0x1d, 0xeb, 0xc1, 0xff, 0xc3, 0x5c, 0xbf, 0x82, 0x87, 0x5b, 0x0a, 0x95, 0x7b,
	0x64, 0x95, 0x7b, 0xe4, 0x35, 0xa0, 0x76, 0x3e, 0x99, 0xaa, 0xf9, 0xf1, 0x1f, 0x36, 0x2c, 0xfe,
	0xac, 0x58, 0x0c, 0x9d, 0xd5, 0x8c, 0x6c, 0x7f, 0x3b, 0x29, 0x52, 0x7b, 0xef, 0xf1, 0x5b, 0x59,
	0x7b, 0xbd, 0x1f, 0xfe, 0xfa, 0xfb, 0x67, 0xfb, 0xbe, 0xc7, 0xf0, 0xa7, 0xae, 0x94, 0x3b, 0x80,
	0xb6, 0x39, 0x3f, 0xcc, 0x48, 0xb5, 0x61, 0xae, 0x7a, 0x86, 0x8e, 0xcd, 0xaf, 0xad, 0xe7, 0x52,
	0x09, 0xe6, 0x75, 0xb1, 0xc4, 0x4a, 0xc2, 0x10, 0xda, 0xe6, 0xc3, 0x67, 0x16, 0xd8, 0xf0, 0x59,
	0xed, 0xed, 0xbd, 0xe5, 0x59, 0x5e, 0xad, 0x62, 0xba, 0x07, 0x75, 0xfa, 0xef, 0x7c, 0xfe, 0x6f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xdc, 0x27, 0x88, 0xc7, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FacilityClient is the client API for Facility service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FacilityClient interface {
	CreateFacility(ctx context.Context, in *CreateFacilityRequest, opts ...grpc.CallOption) (*CreateFacilityReply, error)
	EditFacility(ctx context.Context, in *EditFacilityRequest, opts ...grpc.CallOption) (*GenericReply, error)
	BookFacility(ctx context.Context, in *BookFacilityRequest, opts ...grpc.CallOption) (*BookFacilityReply, error)
}

type facilityClient struct {
	cc *grpc.ClientConn
}

func NewFacilityClient(cc *grpc.ClientConn) FacilityClient {
	return &facilityClient{cc}
}

func (c *facilityClient) CreateFacility(ctx context.Context, in *CreateFacilityRequest, opts ...grpc.CallOption) (*CreateFacilityReply, error) {
	out := new(CreateFacilityReply)
	err := c.cc.Invoke(ctx, "/Facility.Facility/CreateFacility", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilityClient) EditFacility(ctx context.Context, in *EditFacilityRequest, opts ...grpc.CallOption) (*GenericReply, error) {
	out := new(GenericReply)
	err := c.cc.Invoke(ctx, "/Facility.Facility/EditFacility", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilityClient) BookFacility(ctx context.Context, in *BookFacilityRequest, opts ...grpc.CallOption) (*BookFacilityReply, error) {
	out := new(BookFacilityReply)
	err := c.cc.Invoke(ctx, "/Facility.Facility/BookFacility", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FacilityServer is the server API for Facility service.
type FacilityServer interface {
	CreateFacility(context.Context, *CreateFacilityRequest) (*CreateFacilityReply, error)
	EditFacility(context.Context, *EditFacilityRequest) (*GenericReply, error)
	BookFacility(context.Context, *BookFacilityRequest) (*BookFacilityReply, error)
}

// UnimplementedFacilityServer can be embedded to have forward compatible implementations.
type UnimplementedFacilityServer struct {
}

func (*UnimplementedFacilityServer) CreateFacility(ctx context.Context, req *CreateFacilityRequest) (*CreateFacilityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFacility not implemented")
}
func (*UnimplementedFacilityServer) EditFacility(ctx context.Context, req *EditFacilityRequest) (*GenericReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditFacility not implemented")
}
func (*UnimplementedFacilityServer) BookFacility(ctx context.Context, req *BookFacilityRequest) (*BookFacilityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookFacility not implemented")
}

func RegisterFacilityServer(s *grpc.Server, srv FacilityServer) {
	s.RegisterService(&_Facility_serviceDesc, srv)
}

func _Facility_CreateFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityServer).CreateFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Facility.Facility/CreateFacility",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityServer).CreateFacility(ctx, req.(*CreateFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facility_EditFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityServer).EditFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Facility.Facility/EditFacility",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityServer).EditFacility(ctx, req.(*EditFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Facility_BookFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityServer).BookFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Facility.Facility/BookFacility",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityServer).BookFacility(ctx, req.(*BookFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Facility_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Facility.Facility",
	HandlerType: (*FacilityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFacility",
			Handler:    _Facility_CreateFacility_Handler,
		},
		{
			MethodName: "EditFacility",
			Handler:    _Facility_EditFacility_Handler,
		},
		{
			MethodName: "BookFacility",
			Handler:    _Facility_BookFacility_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/athFacility/v1/athFacility.proto",
}
