// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/athVenue/v1/athVenue.proto

package Venue

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteVenueHolidayRequest struct {
	HolidayId            int32    `protobuf:"varint,1,opt,name=holiday_id,json=holidayId,proto3" json:"holiday_id,omitempty"`
	VenueId              int32    `protobuf:"varint,2,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVenueHolidayRequest) Reset()         { *m = DeleteVenueHolidayRequest{} }
func (m *DeleteVenueHolidayRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteVenueHolidayRequest) ProtoMessage()    {}
func (*DeleteVenueHolidayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b427831c7bf93564, []int{0}
}

func (m *DeleteVenueHolidayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVenueHolidayRequest.Unmarshal(m, b)
}
func (m *DeleteVenueHolidayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVenueHolidayRequest.Marshal(b, m, deterministic)
}
func (m *DeleteVenueHolidayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVenueHolidayRequest.Merge(m, src)
}
func (m *DeleteVenueHolidayRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteVenueHolidayRequest.Size(m)
}
func (m *DeleteVenueHolidayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVenueHolidayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVenueHolidayRequest proto.InternalMessageInfo

func (m *DeleteVenueHolidayRequest) GetHolidayId() int32 {
	if m != nil {
		return m.HolidayId
	}
	return 0
}

func (m *DeleteVenueHolidayRequest) GetVenueId() int32 {
	if m != nil {
		return m.VenueId
	}
	return 0
}

type GenericReply struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericReply) Reset()         { *m = GenericReply{} }
func (m *GenericReply) String() string { return proto.CompactTextString(m) }
func (*GenericReply) ProtoMessage()    {}
func (*GenericReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b427831c7bf93564, []int{1}
}

func (m *GenericReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericReply.Unmarshal(m, b)
}
func (m *GenericReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericReply.Marshal(b, m, deterministic)
}
func (m *GenericReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericReply.Merge(m, src)
}
func (m *GenericReply) XXX_Size() int {
	return xxx_messageInfo_GenericReply.Size(m)
}
func (m *GenericReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericReply.DiscardUnknown(m)
}

var xxx_messageInfo_GenericReply proto.InternalMessageInfo

func (m *GenericReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *GenericReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GenericReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateVenueHolidayRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Day                  int32    `protobuf:"varint,2,opt,name=day,proto3" json:"day,omitempty"`
	Month                string   `protobuf:"bytes,3,opt,name=month,proto3" json:"month,omitempty"`
	Year                 string   `protobuf:"bytes,4,opt,name=year,proto3" json:"year,omitempty"`
	VenueId              int32    `protobuf:"varint,5,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	CreatedBy            int32    `protobuf:"varint,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVenueHolidayRequest) Reset()         { *m = CreateVenueHolidayRequest{} }
func (m *CreateVenueHolidayRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVenueHolidayRequest) ProtoMessage()    {}
func (*CreateVenueHolidayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b427831c7bf93564, []int{2}
}

func (m *CreateVenueHolidayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVenueHolidayRequest.Unmarshal(m, b)
}
func (m *CreateVenueHolidayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVenueHolidayRequest.Marshal(b, m, deterministic)
}
func (m *CreateVenueHolidayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVenueHolidayRequest.Merge(m, src)
}
func (m *CreateVenueHolidayRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVenueHolidayRequest.Size(m)
}
func (m *CreateVenueHolidayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVenueHolidayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVenueHolidayRequest proto.InternalMessageInfo

func (m *CreateVenueHolidayRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateVenueHolidayRequest) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *CreateVenueHolidayRequest) GetMonth() string {
	if m != nil {
		return m.Month
	}
	return ""
}

func (m *CreateVenueHolidayRequest) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func (m *CreateVenueHolidayRequest) GetVenueId() int32 {
	if m != nil {
		return m.VenueId
	}
	return 0
}

func (m *CreateVenueHolidayRequest) GetCreatedBy() int32 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

type CreateVenueHolidayReply struct {
	Data                 *CreateVenueHolidayReplyData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status               bool                         `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string                       `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error                string                       `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *CreateVenueHolidayReply) Reset()         { *m = CreateVenueHolidayReply{} }
func (m *CreateVenueHolidayReply) String() string { return proto.CompactTextString(m) }
func (*CreateVenueHolidayReply) ProtoMessage()    {}
func (*CreateVenueHolidayReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b427831c7bf93564, []int{3}
}

func (m *CreateVenueHolidayReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVenueHolidayReply.Unmarshal(m, b)
}
func (m *CreateVenueHolidayReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVenueHolidayReply.Marshal(b, m, deterministic)
}
func (m *CreateVenueHolidayReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVenueHolidayReply.Merge(m, src)
}
func (m *CreateVenueHolidayReply) XXX_Size() int {
	return xxx_messageInfo_CreateVenueHolidayReply.Size(m)
}
func (m *CreateVenueHolidayReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVenueHolidayReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVenueHolidayReply proto.InternalMessageInfo

func (m *CreateVenueHolidayReply) GetData() *CreateVenueHolidayReplyData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateVenueHolidayReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *CreateVenueHolidayReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateVenueHolidayReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateVenueHolidayReplyData struct {
	HolidayId            int32    `protobuf:"varint,1,opt,name=holiday_id,json=holidayId,proto3" json:"holiday_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVenueHolidayReplyData) Reset()         { *m = CreateVenueHolidayReplyData{} }
func (m *CreateVenueHolidayReplyData) String() string { return proto.CompactTextString(m) }
func (*CreateVenueHolidayReplyData) ProtoMessage()    {}
func (*CreateVenueHolidayReplyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b427831c7bf93564, []int{4}
}

func (m *CreateVenueHolidayReplyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVenueHolidayReplyData.Unmarshal(m, b)
}
func (m *CreateVenueHolidayReplyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVenueHolidayReplyData.Marshal(b, m, deterministic)
}
func (m *CreateVenueHolidayReplyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVenueHolidayReplyData.Merge(m, src)
}
func (m *CreateVenueHolidayReplyData) XXX_Size() int {
	return xxx_messageInfo_CreateVenueHolidayReplyData.Size(m)
}
func (m *CreateVenueHolidayReplyData) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVenueHolidayReplyData.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVenueHolidayReplyData proto.InternalMessageInfo

func (m *CreateVenueHolidayReplyData) GetHolidayId() int32 {
	if m != nil {
		return m.HolidayId
	}
	return 0
}

type EditVenueRequest struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string           `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Address              string           `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string           `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string           `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	UpdatedBy            int32            `protobuf:"varint,6,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	GetLat               string           `protobuf:"bytes,7,opt,name=get_lat,json=getLat,proto3" json:"get_lat,omitempty"`
	GetLong              string           `protobuf:"bytes,8,opt,name=get_long,json=getLong,proto3" json:"get_long,omitempty"`
	Amenities            string           `protobuf:"bytes,9,opt,name=amenities,proto3" json:"amenities,omitempty"`
	VenueId              int32            `protobuf:"varint,10,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	Hours                map[int32]string `protobuf:"bytes,11,rep,name=hours,proto3" json:"hours,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DeleteHours          []int32          `protobuf:"varint,12,rep,packed,name=delete_hours,json=deleteHours,proto3" json:"delete_hours,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *EditVenueRequest) Reset()         { *m = EditVenueRequest{} }
func (m *EditVenueRequest) String() string { return proto.CompactTextString(m) }
func (*EditVenueRequest) ProtoMessage()    {}
func (*EditVenueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b427831c7bf93564, []int{5}
}

func (m *EditVenueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditVenueRequest.Unmarshal(m, b)
}
func (m *EditVenueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditVenueRequest.Marshal(b, m, deterministic)
}
func (m *EditVenueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditVenueRequest.Merge(m, src)
}
func (m *EditVenueRequest) XXX_Size() int {
	return xxx_messageInfo_EditVenueRequest.Size(m)
}
func (m *EditVenueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditVenueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditVenueRequest proto.InternalMessageInfo

func (m *EditVenueRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditVenueRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *EditVenueRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *EditVenueRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *EditVenueRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EditVenueRequest) GetUpdatedBy() int32 {
	if m != nil {
		return m.UpdatedBy
	}
	return 0
}

func (m *EditVenueRequest) GetGetLat() string {
	if m != nil {
		return m.GetLat
	}
	return ""
}

func (m *EditVenueRequest) GetGetLong() string {
	if m != nil {
		return m.GetLong
	}
	return ""
}

func (m *EditVenueRequest) GetAmenities() string {
	if m != nil {
		return m.Amenities
	}
	return ""
}

func (m *EditVenueRequest) GetVenueId() int32 {
	if m != nil {
		return m.VenueId
	}
	return 0
}

func (m *EditVenueRequest) GetHours() map[int32]string {
	if m != nil {
		return m.Hours
	}
	return nil
}

func (m *EditVenueRequest) GetDeleteHours() []int32 {
	if m != nil {
		return m.DeleteHours
	}
	return nil
}

type CreateVenueRequest struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string           `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Address              string           `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone                string           `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string           `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	CompanyId            int32            `protobuf:"varint,6,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	CreatedBy            int32            `protobuf:"varint,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	GetLat               string           `protobuf:"bytes,8,opt,name=get_lat,json=getLat,proto3" json:"get_lat,omitempty"`
	GetLong              string           `protobuf:"bytes,9,opt,name=get_long,json=getLong,proto3" json:"get_long,omitempty"`
	Amenities            string           `protobuf:"bytes,10,opt,name=amenities,proto3" json:"amenities,omitempty"`
	Hours                map[int32]string `protobuf:"bytes,11,rep,name=hours,proto3" json:"hours,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateVenueRequest) Reset()         { *m = CreateVenueRequest{} }
func (m *CreateVenueRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVenueRequest) ProtoMessage()    {}
func (*CreateVenueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b427831c7bf93564, []int{6}
}

func (m *CreateVenueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVenueRequest.Unmarshal(m, b)
}
func (m *CreateVenueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVenueRequest.Marshal(b, m, deterministic)
}
func (m *CreateVenueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVenueRequest.Merge(m, src)
}
func (m *CreateVenueRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVenueRequest.Size(m)
}
func (m *CreateVenueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVenueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVenueRequest proto.InternalMessageInfo

func (m *CreateVenueRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateVenueRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateVenueRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateVenueRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreateVenueRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateVenueRequest) GetCompanyId() int32 {
	if m != nil {
		return m.CompanyId
	}
	return 0
}

func (m *CreateVenueRequest) GetCreatedBy() int32 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *CreateVenueRequest) GetGetLat() string {
	if m != nil {
		return m.GetLat
	}
	return ""
}

func (m *CreateVenueRequest) GetGetLong() string {
	if m != nil {
		return m.GetLong
	}
	return ""
}

func (m *CreateVenueRequest) GetAmenities() string {
	if m != nil {
		return m.Amenities
	}
	return ""
}

func (m *CreateVenueRequest) GetHours() map[int32]string {
	if m != nil {
		return m.Hours
	}
	return nil
}

type CreateVenueReply struct {
	Data                 *CreateVenuepReplyData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status               bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error                string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateVenueReply) Reset()         { *m = CreateVenueReply{} }
func (m *CreateVenueReply) String() string { return proto.CompactTextString(m) }
func (*CreateVenueReply) ProtoMessage()    {}
func (*CreateVenueReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b427831c7bf93564, []int{7}
}

func (m *CreateVenueReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVenueReply.Unmarshal(m, b)
}
func (m *CreateVenueReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVenueReply.Marshal(b, m, deterministic)
}
func (m *CreateVenueReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVenueReply.Merge(m, src)
}
func (m *CreateVenueReply) XXX_Size() int {
	return xxx_messageInfo_CreateVenueReply.Size(m)
}
func (m *CreateVenueReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVenueReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVenueReply proto.InternalMessageInfo

func (m *CreateVenueReply) GetData() *CreateVenuepReplyData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateVenueReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *CreateVenueReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateVenueReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateVenuepReplyData struct {
	VenueId              int32    `protobuf:"varint,1,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVenuepReplyData) Reset()         { *m = CreateVenuepReplyData{} }
func (m *CreateVenuepReplyData) String() string { return proto.CompactTextString(m) }
func (*CreateVenuepReplyData) ProtoMessage()    {}
func (*CreateVenuepReplyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b427831c7bf93564, []int{8}
}

func (m *CreateVenuepReplyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVenuepReplyData.Unmarshal(m, b)
}
func (m *CreateVenuepReplyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVenuepReplyData.Marshal(b, m, deterministic)
}
func (m *CreateVenuepReplyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVenuepReplyData.Merge(m, src)
}
func (m *CreateVenuepReplyData) XXX_Size() int {
	return xxx_messageInfo_CreateVenuepReplyData.Size(m)
}
func (m *CreateVenuepReplyData) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVenuepReplyData.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVenuepReplyData proto.InternalMessageInfo

func (m *CreateVenuepReplyData) GetVenueId() int32 {
	if m != nil {
		return m.VenueId
	}
	return 0
}

func init() {
	proto.RegisterType((*DeleteVenueHolidayRequest)(nil), "Venue.DeleteVenueHolidayRequest")
	proto.RegisterType((*GenericReply)(nil), "Venue.GenericReply")
	proto.RegisterType((*CreateVenueHolidayRequest)(nil), "Venue.CreateVenueHolidayRequest")
	proto.RegisterType((*CreateVenueHolidayReply)(nil), "Venue.CreateVenueHolidayReply")
	proto.RegisterType((*CreateVenueHolidayReplyData)(nil), "Venue.CreateVenueHolidayReplyData")
	proto.RegisterType((*EditVenueRequest)(nil), "Venue.EditVenueRequest")
	proto.RegisterMapType((map[int32]string)(nil), "Venue.EditVenueRequest.HoursEntry")
	proto.RegisterType((*CreateVenueRequest)(nil), "Venue.CreateVenueRequest")
	proto.RegisterMapType((map[int32]string)(nil), "Venue.CreateVenueRequest.HoursEntry")
	proto.RegisterType((*CreateVenueReply)(nil), "Venue.CreateVenueReply")
	proto.RegisterType((*CreateVenuepReplyData)(nil), "Venue.CreateVenuepReplyData")
}

func init() { proto.RegisterFile("api/athVenue/v1/athVenue.proto", fileDescriptor_b427831c7bf93564) }

var fileDescriptor_b427831c7bf93564 = []byte{
	// 723 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0x96, 0xe3, 0x38, 0x89, 0x4f, 0x7a, 0xd5, 0xde, 0xb9, 0x6d, 0xe3, 0xe4, 0x96, 0x2a, 0x58,
	0x2c, 0xba, 0x6a, 0xa1, 0x48, 0xa8, 0xaa, 0x58, 0x95, 0x56, 0xb4, 0x12, 0x0b, 0x64, 0x89, 0x2e,
	0xd8, 0x44, 0xd3, 0x78, 0xe4, 0x58, 0x75, 0x66, 0x8c, 0x3d, 0x89, 0xe4, 0x2d, 0x6b, 0x76, 0x48,
	0x48, 0xf0, 0x02, 0xac, 0x79, 0x16, 0x5e, 0x81, 0x07, 0x41, 0x73, 0xc6, 0x6e, 0xed, 0x24, 0x0e,
	0x0b, 0x84, 0xc4, 0x6e, 0xce, 0xff, 0x99, 0xef, 0x3b, 0x67, 0x06, 0xf6, 0x69, 0x1c, 0x1e, 0x51,
	0x39, 0xb9, 0x66, 0x7c, 0xc6, 0x8e, 0xe6, 0x4f, 0xee, 0xce, 0x87, 0x71, 0x22, 0xa4, 0x20, 0x16,
	0x0a, 0x83, 0xbd, 0x40, 0x88, 0x20, 0x62, 0x47, 0xe8, 0xcd, 0xb9, 0x90, 0x54, 0x86, 0x82, 0xa7,
	0xda, 0xc9, 0x7d, 0x03, 0xfd, 0x73, 0x16, 0x31, 0xc9, 0xd0, 0xf9, 0x52, 0x44, 0xa1, 0x4f, 0x33,
	0x8f, 0xbd, 0x9b, 0xb1, 0x54, 0x92, 0x07, 0x00, 0x13, 0xad, 0x19, 0x85, 0xbe, 0x63, 0x0c, 0x8d,
	0x03, 0xcb, 0xb3, 0x73, 0xcd, 0x95, 0x4f, 0xfa, 0xd0, 0x99, 0xab, 0x28, 0x65, 0x6c, 0xa0, 0xb1,
	0x8d, 0xf2, 0x95, 0xef, 0x5e, 0xc3, 0xc6, 0x4b, 0xc6, 0x59, 0x12, 0x8e, 0x3d, 0x16, 0x47, 0x19,
	0xd9, 0x85, 0x56, 0x2a, 0xa9, 0x9c, 0xa5, 0x98, 0xa5, 0xe3, 0xe5, 0x12, 0x71, 0xa0, 0x3d, 0x65,
	0x69, 0x4a, 0x03, 0x86, 0x19, 0x6c, 0xaf, 0x10, 0xc9, 0x36, 0x58, 0x2c, 0x49, 0x44, 0xe2, 0x98,
	0xa8, 0xd7, 0x82, 0xfb, 0xd5, 0x80, 0xfe, 0x8b, 0x84, 0xd1, 0xd5, 0xfd, 0x6e, 0x83, 0x25, 0x43,
	0x19, 0x31, 0x2c, 0x62, 0x7b, 0x5a, 0x20, 0x5b, 0x60, 0xfa, 0x34, 0xcb, 0x3b, 0x54, 0x47, 0xe5,
	0x37, 0x15, 0x5c, 0x4e, 0x8a, 0xdc, 0x28, 0x10, 0x02, 0xcd, 0x8c, 0xd1, 0xc4, 0x69, 0xa2, 0x12,
	0xcf, 0x95, 0x2b, 0x5a, 0x95, 0x2b, 0x2a, 0x70, 0xc6, 0xd8, 0x89, 0x3f, 0xba, 0xc9, 0x9c, 0x96,
	0x06, 0x27, 0xd7, 0x9c, 0x65, 0xee, 0x67, 0x03, 0x7a, 0xab, 0x3a, 0x55, 0x68, 0x3c, 0x83, 0xa6,
	0x4f, 0x25, 0xc5, 0x36, 0xbb, 0xc7, 0xee, 0xa1, 0x66, 0xad, 0xc6, 0xfb, 0x9c, 0x4a, 0xea, 0xa1,
	0x7f, 0x09, 0xc5, 0x46, 0x1d, 0x8a, 0x66, 0x0d, 0x8a, 0xcd, 0x32, 0x8a, 0xcf, 0xe1, 0xff, 0x35,
	0xc5, 0x7e, 0x41, 0xbb, 0xfb, 0xcd, 0x84, 0xad, 0x0b, 0x3f, 0x94, 0x18, 0x5c, 0x40, 0x4f, 0xa0,
	0xc9, 0xe9, 0xb4, 0x40, 0x1e, 0xcf, 0x64, 0x08, 0x5d, 0x9f, 0xa5, 0xe3, 0x24, 0x8c, 0xd5, 0xc4,
	0xe5, 0x04, 0x97, 0x55, 0xaa, 0x71, 0xea, 0xfb, 0x09, 0x4b, 0xd3, 0xa2, 0xf1, 0x5c, 0x54, 0x8d,
	0xc7, 0x13, 0xc1, 0x59, 0xd1, 0x38, 0x0a, 0x78, 0x9d, 0x29, 0x0d, 0x23, 0xe4, 0x42, 0x5d, 0x47,
	0x09, 0xaa, 0xdf, 0x59, 0xec, 0x2f, 0x30, 0x91, 0x6b, 0xce, 0x32, 0xd2, 0x83, 0x76, 0xc0, 0xe4,
	0x28, 0xa2, 0xd2, 0x69, 0x63, 0x58, 0x2b, 0x60, 0xf2, 0x15, 0x95, 0x8a, 0x5c, 0x34, 0x08, 0x1e,
	0x38, 0x1d, 0x5d, 0x5e, 0x59, 0x04, 0x0f, 0xc8, 0x1e, 0xd8, 0x74, 0xca, 0x78, 0x28, 0x43, 0x96,
	0x3a, 0x36, 0xda, 0xee, 0x15, 0x95, 0xa9, 0x80, 0xea, 0x54, 0x9c, 0x80, 0x35, 0x11, 0xb3, 0x24,
	0x75, 0xba, 0x43, 0xb3, 0xc4, 0xed, 0x22, 0x5e, 0x87, 0x97, 0xca, 0xe9, 0x82, 0xcb, 0x24, 0xf3,
	0x74, 0x00, 0x79, 0x08, 0x1b, 0x3e, 0x6e, 0xe2, 0x48, 0x27, 0xd8, 0x18, 0x9a, 0x07, 0x96, 0x82,
	0x4b, 0xe9, 0xd0, 0x7d, 0x70, 0x02, 0x70, 0x1f, 0xa7, 0xe6, 0xfa, 0x96, 0x65, 0x39, 0x3f, 0xea,
	0xa8, 0xe0, 0x99, 0xd3, 0x68, 0x56, 0xec, 0x92, 0x16, 0x4e, 0x1b, 0x27, 0x86, 0xfb, 0xc9, 0x04,
	0x52, 0xa2, 0xfc, 0x2f, 0x61, 0x6d, 0x2c, 0xa6, 0x31, 0xe5, 0x38, 0x65, 0xc5, 0xfe, 0x68, 0xcd,
	0xd2, 0x7a, 0xb5, 0x17, 0xd6, 0xab, 0x4c, 0x6a, 0xa7, 0x96, 0x54, 0x7b, 0x0d, 0xa9, 0xb0, 0x48,
	0xea, 0x69, 0x95, 0xb9, 0x47, 0xcb, 0x5b, 0x59, 0xcb, 0xdd, 0x6f, 0x10, 0xf3, 0xc1, 0x80, 0xad,
	0x4a, 0x09, 0xf5, 0x3e, 0x3c, 0xae, 0xbc, 0x0f, 0x7b, 0xcb, 0x9d, 0xc4, 0x7f, 0xea, 0x65, 0x38,
	0x86, 0x9d, 0x95, 0x65, 0x2a, 0x23, 0x6f, 0x54, 0x46, 0xfe, 0xf8, 0x8b, 0x09, 0xfa, 0xab, 0x21,
	0x6f, 0xa1, 0x5b, 0x8a, 0x26, 0xfd, 0x5a, 0x08, 0x07, 0xbd, 0x55, 0xa6, 0x38, 0xca, 0xdc, 0xde,
	0xfb, 0xef, 0x3f, 0x3e, 0x36, 0xfe, 0x75, 0x37, 0xd5, 0x87, 0x56, 0x4e, 0xf6, 0x1a, 0xec, 0xbb,
	0x25, 0x22, 0xbd, 0x9a, 0xb5, 0x1a, 0xfc, 0x97, 0x1b, 0xca, 0x9f, 0x8f, 0xbb, 0x83, 0x39, 0x37,
	0xdd, 0x7f, 0x54, 0xce, 0xfb, 0x24, 0xf3, 0xca, 0x4a, 0xe4, 0xaf, 0x20, 0x19, 0xae, 0x79, 0x8d,
	0x75, 0x8d, 0xfd, 0xf5, 0xef, 0xb5, 0xbb, 0x8f, 0xe5, 0x1c, 0x77, 0x77, 0xe1, 0x0a, 0x45, 0x85,
	0x5b, 0x20, 0xcb, 0x5f, 0xee, 0x5d, 0xdd, 0xda, 0xdf, 0x78, 0xf5, 0xdd, 0x2a, 0xc5, 0x96, 0x63,
	0x6f, 0x5a, 0xf8, 0xcd, 0x3f, 0xfd, 0x19, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xb0, 0xf3, 0x60, 0x2d,
	0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VenueClient is the client API for Venue service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VenueClient interface {
	CreateVenue(ctx context.Context, in *CreateVenueRequest, opts ...grpc.CallOption) (*CreateVenueReply, error)
	EditVenue(ctx context.Context, in *EditVenueRequest, opts ...grpc.CallOption) (*GenericReply, error)
	CreateVenueHoliday(ctx context.Context, in *CreateVenueHolidayRequest, opts ...grpc.CallOption) (*CreateVenueHolidayReply, error)
	DeleteVenueHoliday(ctx context.Context, in *DeleteVenueHolidayRequest, opts ...grpc.CallOption) (*GenericReply, error)
}

type venueClient struct {
	cc *grpc.ClientConn
}

func NewVenueClient(cc *grpc.ClientConn) VenueClient {
	return &venueClient{cc}
}

func (c *venueClient) CreateVenue(ctx context.Context, in *CreateVenueRequest, opts ...grpc.CallOption) (*CreateVenueReply, error) {
	out := new(CreateVenueReply)
	err := c.cc.Invoke(ctx, "/Venue.Venue/CreateVenue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueClient) EditVenue(ctx context.Context, in *EditVenueRequest, opts ...grpc.CallOption) (*GenericReply, error) {
	out := new(GenericReply)
	err := c.cc.Invoke(ctx, "/Venue.Venue/EditVenue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueClient) CreateVenueHoliday(ctx context.Context, in *CreateVenueHolidayRequest, opts ...grpc.CallOption) (*CreateVenueHolidayReply, error) {
	out := new(CreateVenueHolidayReply)
	err := c.cc.Invoke(ctx, "/Venue.Venue/CreateVenueHoliday", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueClient) DeleteVenueHoliday(ctx context.Context, in *DeleteVenueHolidayRequest, opts ...grpc.CallOption) (*GenericReply, error) {
	out := new(GenericReply)
	err := c.cc.Invoke(ctx, "/Venue.Venue/DeleteVenueHoliday", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VenueServer is the server API for Venue service.
type VenueServer interface {
	CreateVenue(context.Context, *CreateVenueRequest) (*CreateVenueReply, error)
	EditVenue(context.Context, *EditVenueRequest) (*GenericReply, error)
	CreateVenueHoliday(context.Context, *CreateVenueHolidayRequest) (*CreateVenueHolidayReply, error)
	DeleteVenueHoliday(context.Context, *DeleteVenueHolidayRequest) (*GenericReply, error)
}

// UnimplementedVenueServer can be embedded to have forward compatible implementations.
type UnimplementedVenueServer struct {
}

func (*UnimplementedVenueServer) CreateVenue(ctx context.Context, req *CreateVenueRequest) (*CreateVenueReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVenue not implemented")
}
func (*UnimplementedVenueServer) EditVenue(ctx context.Context, req *EditVenueRequest) (*GenericReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditVenue not implemented")
}
func (*UnimplementedVenueServer) CreateVenueHoliday(ctx context.Context, req *CreateVenueHolidayRequest) (*CreateVenueHolidayReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVenueHoliday not implemented")
}
func (*UnimplementedVenueServer) DeleteVenueHoliday(ctx context.Context, req *DeleteVenueHolidayRequest) (*GenericReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVenueHoliday not implemented")
}

func RegisterVenueServer(s *grpc.Server, srv VenueServer) {
	s.RegisterService(&_Venue_serviceDesc, srv)
}

func _Venue_CreateVenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServer).CreateVenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Venue.Venue/CreateVenue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServer).CreateVenue(ctx, req.(*CreateVenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Venue_EditVenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditVenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServer).EditVenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Venue.Venue/EditVenue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServer).EditVenue(ctx, req.(*EditVenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Venue_CreateVenueHoliday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVenueHolidayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServer).CreateVenueHoliday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Venue.Venue/CreateVenueHoliday",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServer).CreateVenueHoliday(ctx, req.(*CreateVenueHolidayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Venue_DeleteVenueHoliday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVenueHolidayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServer).DeleteVenueHoliday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Venue.Venue/DeleteVenueHoliday",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServer).DeleteVenueHoliday(ctx, req.(*DeleteVenueHolidayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Venue_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Venue.Venue",
	HandlerType: (*VenueServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVenue",
			Handler:    _Venue_CreateVenue_Handler,
		},
		{
			MethodName: "EditVenue",
			Handler:    _Venue_EditVenue_Handler,
		},
		{
			MethodName: "CreateVenueHoliday",
			Handler:    _Venue_CreateVenueHoliday_Handler,
		},
		{
			MethodName: "DeleteVenueHoliday",
			Handler:    _Venue_DeleteVenueHoliday_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/athVenue/v1/athVenue.proto",
}
