// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/athCustomer/v1/athCustomer.proto

package Customer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EditCustomerRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	UpdatedBy            int32    `protobuf:"varint,4,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UserId               int32    `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditCustomerRequest) Reset()         { *m = EditCustomerRequest{} }
func (m *EditCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*EditCustomerRequest) ProtoMessage()    {}
func (*EditCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45b146f0a5b71790, []int{0}
}

func (m *EditCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditCustomerRequest.Unmarshal(m, b)
}
func (m *EditCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditCustomerRequest.Marshal(b, m, deterministic)
}
func (m *EditCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditCustomerRequest.Merge(m, src)
}
func (m *EditCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_EditCustomerRequest.Size(m)
}
func (m *EditCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditCustomerRequest proto.InternalMessageInfo

func (m *EditCustomerRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *EditCustomerRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *EditCustomerRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *EditCustomerRequest) GetUpdatedBy() int32 {
	if m != nil {
		return m.UpdatedBy
	}
	return 0
}

func (m *EditCustomerRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CreateCustomerRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	UserSource           string   `protobuf:"bytes,5,opt,name=user_source,json=userSource,proto3" json:"user_source,omitempty"`
	CreatedBy            int32    `protobuf:"varint,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCustomerRequest) Reset()         { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()    {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_45b146f0a5b71790, []int{1}
}

func (m *CreateCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerRequest.Unmarshal(m, b)
}
func (m *CreateCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerRequest.Marshal(b, m, deterministic)
}
func (m *CreateCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerRequest.Merge(m, src)
}
func (m *CreateCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerRequest.Size(m)
}
func (m *CreateCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerRequest proto.InternalMessageInfo

func (m *CreateCustomerRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateCustomerRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateCustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateCustomerRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreateCustomerRequest) GetUserSource() string {
	if m != nil {
		return m.UserSource
	}
	return ""
}

func (m *CreateCustomerRequest) GetCreatedBy() int32 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

type CreateCustomerReply struct {
	Data                 *CreateCustomerReplyData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status               bool                     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string                   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error                string                   `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *CreateCustomerReply) Reset()         { *m = CreateCustomerReply{} }
func (m *CreateCustomerReply) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerReply) ProtoMessage()    {}
func (*CreateCustomerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_45b146f0a5b71790, []int{2}
}

func (m *CreateCustomerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerReply.Unmarshal(m, b)
}
func (m *CreateCustomerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerReply.Marshal(b, m, deterministic)
}
func (m *CreateCustomerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerReply.Merge(m, src)
}
func (m *CreateCustomerReply) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerReply.Size(m)
}
func (m *CreateCustomerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerReply proto.InternalMessageInfo

func (m *CreateCustomerReply) GetData() *CreateCustomerReplyData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateCustomerReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *CreateCustomerReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateCustomerReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateCustomerReplyData struct {
	CustomerId           int32    `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCustomerReplyData) Reset()         { *m = CreateCustomerReplyData{} }
func (m *CreateCustomerReplyData) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerReplyData) ProtoMessage()    {}
func (*CreateCustomerReplyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_45b146f0a5b71790, []int{3}
}

func (m *CreateCustomerReplyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerReplyData.Unmarshal(m, b)
}
func (m *CreateCustomerReplyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerReplyData.Marshal(b, m, deterministic)
}
func (m *CreateCustomerReplyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerReplyData.Merge(m, src)
}
func (m *CreateCustomerReplyData) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerReplyData.Size(m)
}
func (m *CreateCustomerReplyData) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerReplyData.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerReplyData proto.InternalMessageInfo

func (m *CreateCustomerReplyData) GetCustomerId() int32 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

type GenericReply struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericReply) Reset()         { *m = GenericReply{} }
func (m *GenericReply) String() string { return proto.CompactTextString(m) }
func (*GenericReply) ProtoMessage()    {}
func (*GenericReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_45b146f0a5b71790, []int{4}
}

func (m *GenericReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericReply.Unmarshal(m, b)
}
func (m *GenericReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericReply.Marshal(b, m, deterministic)
}
func (m *GenericReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericReply.Merge(m, src)
}
func (m *GenericReply) XXX_Size() int {
	return xxx_messageInfo_GenericReply.Size(m)
}
func (m *GenericReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericReply.DiscardUnknown(m)
}

var xxx_messageInfo_GenericReply proto.InternalMessageInfo

func (m *GenericReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *GenericReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GenericReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_45b146f0a5b71790, []int{5}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*EditCustomerRequest)(nil), "Customer.EditCustomerRequest")
	proto.RegisterType((*CreateCustomerRequest)(nil), "Customer.CreateCustomerRequest")
	proto.RegisterType((*CreateCustomerReply)(nil), "Customer.CreateCustomerReply")
	proto.RegisterType((*CreateCustomerReplyData)(nil), "Customer.CreateCustomerReplyData")
	proto.RegisterType((*GenericReply)(nil), "Customer.GenericReply")
	proto.RegisterType((*Empty)(nil), "Customer.Empty")
}

func init() {
	proto.RegisterFile("api/athCustomer/v1/athCustomer.proto", fileDescriptor_45b146f0a5b71790)
}

var fileDescriptor_45b146f0a5b71790 = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xbf, 0x6e, 0xd5, 0x30,
	0x14, 0xc6, 0xe5, 0xdb, 0xfb, 0x2f, 0xa7, 0x15, 0x42, 0x6e, 0x69, 0xa3, 0x40, 0xd5, 0x62, 0x31,
	0x74, 0xea, 0x15, 0x45, 0x2c, 0x8c, 0x2d, 0x15, 0xea, 0xc2, 0x10, 0x24, 0xd6, 0xc8, 0x4d, 0x0e,
	0xb7, 0x91, 0x92, 0x38, 0xd8, 0x0e, 0x52, 0x56, 0x5e, 0x01, 0x76, 0x1e, 0x85, 0x87, 0x60, 0x62,
	0xe7, 0x41, 0x90, 0x4f, 0xe2, 0xde, 0x50, 0x35, 0x4c, 0x1d, 0xbf, 0xef, 0x9c, 0xd8, 0xbf, 0xef,
	0xc4, 0x07, 0x5e, 0xc8, 0x3a, 0x5f, 0x49, 0x7b, 0x73, 0xd1, 0x18, 0xab, 0x4a, 0xd4, 0xab, 0x2f,
	0x2f, 0x87, 0xf2, 0xb4, 0xd6, 0xca, 0x2a, 0xbe, 0xf4, 0x3a, 0x7a, 0xb6, 0x56, 0x6a, 0x5d, 0xe0,
	0x8a, 0x3e, 0xab, 0x2a, 0x65, 0xa5, 0xcd, 0x55, 0x65, 0xba, 0x3e, 0xf1, 0x83, 0xc1, 0xee, 0x65,
	0x96, 0x5b, 0xdf, 0x1e, 0xe3, 0xe7, 0x06, 0x8d, 0xe5, 0x87, 0x00, 0x9f, 0x72, 0x6d, 0x6c, 0x52,
	0xc9, 0x12, 0x43, 0x76, 0xcc, 0x4e, 0x82, 0x38, 0x20, 0xe7, 0xbd, 0x2c, 0x91, 0x3f, 0x85, 0xa0,
	0x90, 0xbe, 0x3a, 0xa1, 0xea, 0xd2, 0x19, 0x54, 0xdc, 0x83, 0x59, 0x7d, 0xa3, 0x2a, 0x0c, 0xb7,
	0xa8, 0xd0, 0x09, 0x77, 0x62, 0x53, 0x67, 0xd2, 0x62, 0x96, 0x5c, 0xb7, 0xe1, 0xf4, 0x98, 0x9d,
	0xcc, 0xe2, 0xa0, 0x77, 0xce, 0x5b, 0x7e, 0x00, 0x8b, 0xc6, 0xa0, 0x4e, 0xf2, 0x2c, 0x9c, 0x51,
	0x6d, 0xee, 0xe4, 0x55, 0x26, 0x7e, 0x32, 0x78, 0x72, 0xa1, 0x51, 0x5a, 0x7c, 0x60, 0x46, 0x2c,
	0x65, 0x5e, 0x78, 0x46, 0x12, 0x1b, 0xf2, 0xe9, 0x90, 0xfc, 0x08, 0xb6, 0x09, 0xcd, 0xa8, 0x46,
	0xa7, 0x48, 0x78, 0x41, 0x0c, 0xce, 0xfa, 0x40, 0x8e, 0x03, 0x49, 0x89, 0x90, 0xa2, 0xcd, 0xbb,
	0x68, 0xbd, 0x73, 0xde, 0x8a, 0xef, 0x0c, 0x76, 0xef, 0x26, 0xa8, 0x8b, 0x96, 0xbf, 0x86, 0x69,
	0x26, 0xad, 0x24, 0xf2, 0xed, 0xb3, 0xe7, 0xa7, 0xb7, 0xbf, 0xf0, 0x9e, 0xe6, 0xb7, 0xd2, 0xca,
	0x98, 0xda, 0xf9, 0x3e, 0xcc, 0x8d, 0x95, 0xb6, 0x31, 0x14, 0x6a, 0x19, 0xf7, 0x8a, 0x87, 0xb0,
	0x28, 0xd1, 0x18, 0xb9, 0xf6, 0x83, 0xf7, 0x92, 0xc2, 0x6a, 0xad, 0xb4, 0x8f, 0x45, 0x42, 0xbc,
	0x81, 0x83, 0x91, 0x8b, 0x5c, 0xe2, 0xb4, 0x37, 0xdd, 0x0f, 0x61, 0x94, 0x08, 0xbc, 0x75, 0x95,
	0x89, 0x8f, 0xb0, 0xf3, 0x0e, 0x2b, 0xd4, 0x79, 0xda, 0x45, 0xd9, 0x30, 0xb1, 0x31, 0xa6, 0xc9,
	0x08, 0xd3, 0xd6, 0x90, 0x69, 0x01, 0xb3, 0xcb, 0xb2, 0xb6, 0xed, 0xd9, 0x6f, 0x06, 0xb7, 0x4f,
	0x98, 0x17, 0xf0, 0xe8, 0x5f, 0x52, 0x7e, 0x34, 0x3e, 0x2c, 0x7a, 0x1b, 0xd1, 0xe1, 0x7f, 0xa7,
	0x29, 0xa2, 0xaf, 0xbf, 0xfe, 0x7c, 0x9b, 0xec, 0x09, 0xee, 0xb6, 0xe7, 0xce, 0xd9, 0x09, 0xec,
	0x0c, 0x37, 0x82, 0x0f, 0x8e, 0xba, 0x67, 0x53, 0xa2, 0xfd, 0x4d, 0x79, 0x38, 0x12, 0x11, 0xd2,
	0x15, 0x5c, 0x3c, 0x76, 0x57, 0x0c, 0x3f, 0xbc, 0x9e, 0xd3, 0xea, 0xbd, 0xfa, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x91, 0x9b, 0xff, 0x81, 0xca, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerClient is the client API for Customer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerClient interface {
	CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerReply, error)
	EditCustomer(ctx context.Context, in *EditCustomerRequest, opts ...grpc.CallOption) (*GenericReply, error)
}

type customerClient struct {
	cc *grpc.ClientConn
}

func NewCustomerClient(cc *grpc.ClientConn) CustomerClient {
	return &customerClient{cc}
}

func (c *customerClient) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerReply, error) {
	out := new(CreateCustomerReply)
	err := c.cc.Invoke(ctx, "/Customer.Customer/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) EditCustomer(ctx context.Context, in *EditCustomerRequest, opts ...grpc.CallOption) (*GenericReply, error) {
	out := new(GenericReply)
	err := c.cc.Invoke(ctx, "/Customer.Customer/EditCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServer is the server API for Customer service.
type CustomerServer interface {
	CreateCustomer(context.Context, *CreateCustomerRequest) (*CreateCustomerReply, error)
	EditCustomer(context.Context, *EditCustomerRequest) (*GenericReply, error)
}

// UnimplementedCustomerServer can be embedded to have forward compatible implementations.
type UnimplementedCustomerServer struct {
}

func (*UnimplementedCustomerServer) CreateCustomer(ctx context.Context, req *CreateCustomerRequest) (*CreateCustomerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (*UnimplementedCustomerServer) EditCustomer(ctx context.Context, req *EditCustomerRequest) (*GenericReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditCustomer not implemented")
}

func RegisterCustomerServer(s *grpc.Server, srv CustomerServer) {
	s.RegisterService(&_Customer_serviceDesc, srv)
}

func _Customer_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Customer.Customer/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).CreateCustomer(ctx, req.(*CreateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_EditCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).EditCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Customer.Customer/EditCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).EditCustomer(ctx, req.(*EditCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Customer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Customer.Customer",
	HandlerType: (*CustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _Customer_CreateCustomer_Handler,
		},
		{
			MethodName: "EditCustomer",
			Handler:    _Customer_EditCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/athCustomer/v1/athCustomer.proto",
}
