// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/athUser/v1/athUser.proto

package User

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EditUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	CompanyName          string   `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	FullName             string   `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	ContactNo            string   `protobuf:"bytes,4,opt,name=contact_no,json=contactNo,proto3" json:"contact_no,omitempty"`
	UpdatedBy            int32    `protobuf:"varint,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UserId               int32    `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId            int32    `protobuf:"varint,7,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	ProfileId            int32    `protobuf:"varint,8,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditUserRequest) Reset()         { *m = EditUserRequest{} }
func (m *EditUserRequest) String() string { return proto.CompactTextString(m) }
func (*EditUserRequest) ProtoMessage()    {}
func (*EditUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{0}
}

func (m *EditUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditUserRequest.Unmarshal(m, b)
}
func (m *EditUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditUserRequest.Marshal(b, m, deterministic)
}
func (m *EditUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditUserRequest.Merge(m, src)
}
func (m *EditUserRequest) XXX_Size() int {
	return xxx_messageInfo_EditUserRequest.Size(m)
}
func (m *EditUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditUserRequest proto.InternalMessageInfo

func (m *EditUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EditUserRequest) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *EditUserRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *EditUserRequest) GetContactNo() string {
	if m != nil {
		return m.ContactNo
	}
	return ""
}

func (m *EditUserRequest) GetUpdatedBy() int32 {
	if m != nil {
		return m.UpdatedBy
	}
	return 0
}

func (m *EditUserRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *EditUserRequest) GetCompanyId() int32 {
	if m != nil {
		return m.CompanyId
	}
	return 0
}

func (m *EditUserRequest) GetProfileId() int32 {
	if m != nil {
		return m.ProfileId
	}
	return 0
}

type GenericReply struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericReply) Reset()         { *m = GenericReply{} }
func (m *GenericReply) String() string { return proto.CompactTextString(m) }
func (*GenericReply) ProtoMessage()    {}
func (*GenericReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{1}
}

func (m *GenericReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericReply.Unmarshal(m, b)
}
func (m *GenericReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericReply.Marshal(b, m, deterministic)
}
func (m *GenericReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericReply.Merge(m, src)
}
func (m *GenericReply) XXX_Size() int {
	return xxx_messageInfo_GenericReply.Size(m)
}
func (m *GenericReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericReply.DiscardUnknown(m)
}

var xxx_messageInfo_GenericReply proto.InternalMessageInfo

func (m *GenericReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *GenericReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GenericReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ResendCodeRequest struct {
	ContactNo            string   `protobuf:"bytes,1,opt,name=contact_no,json=contactNo,proto3" json:"contact_no,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResendCodeRequest) Reset()         { *m = ResendCodeRequest{} }
func (m *ResendCodeRequest) String() string { return proto.CompactTextString(m) }
func (*ResendCodeRequest) ProtoMessage()    {}
func (*ResendCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{2}
}

func (m *ResendCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResendCodeRequest.Unmarshal(m, b)
}
func (m *ResendCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResendCodeRequest.Marshal(b, m, deterministic)
}
func (m *ResendCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResendCodeRequest.Merge(m, src)
}
func (m *ResendCodeRequest) XXX_Size() int {
	return xxx_messageInfo_ResendCodeRequest.Size(m)
}
func (m *ResendCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResendCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResendCodeRequest proto.InternalMessageInfo

func (m *ResendCodeRequest) GetContactNo() string {
	if m != nil {
		return m.ContactNo
	}
	return ""
}

func (m *ResendCodeRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type EmailVerifyRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailVerifyRequest) Reset()         { *m = EmailVerifyRequest{} }
func (m *EmailVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*EmailVerifyRequest) ProtoMessage()    {}
func (*EmailVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{3}
}

func (m *EmailVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailVerifyRequest.Unmarshal(m, b)
}
func (m *EmailVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailVerifyRequest.Marshal(b, m, deterministic)
}
func (m *EmailVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailVerifyRequest.Merge(m, src)
}
func (m *EmailVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_EmailVerifyRequest.Size(m)
}
func (m *EmailVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailVerifyRequest proto.InternalMessageInfo

func (m *EmailVerifyRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type OtpRequest struct {
	OtpNo                string   `protobuf:"bytes,1,opt,name=otp_no,json=otpNo,proto3" json:"otp_no,omitempty"`
	OtpType              string   `protobuf:"bytes,2,opt,name=otp_type,json=otpType,proto3" json:"otp_type,omitempty"`
	OtpExpiry            int32    `protobuf:"varint,3,opt,name=otp_expiry,json=otpExpiry,proto3" json:"otp_expiry,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OtpRequest) Reset()         { *m = OtpRequest{} }
func (m *OtpRequest) String() string { return proto.CompactTextString(m) }
func (*OtpRequest) ProtoMessage()    {}
func (*OtpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{4}
}

func (m *OtpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OtpRequest.Unmarshal(m, b)
}
func (m *OtpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OtpRequest.Marshal(b, m, deterministic)
}
func (m *OtpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OtpRequest.Merge(m, src)
}
func (m *OtpRequest) XXX_Size() int {
	return xxx_messageInfo_OtpRequest.Size(m)
}
func (m *OtpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OtpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OtpRequest proto.InternalMessageInfo

func (m *OtpRequest) GetOtpNo() string {
	if m != nil {
		return m.OtpNo
	}
	return ""
}

func (m *OtpRequest) GetOtpType() string {
	if m != nil {
		return m.OtpType
	}
	return ""
}

func (m *OtpRequest) GetOtpExpiry() int32 {
	if m != nil {
		return m.OtpExpiry
	}
	return 0
}

func (m *OtpRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ResetPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{5}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ResetPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignupRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	CompanyName          string   `protobuf:"bytes,3,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	FullName             string   `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	ContactNo            string   `protobuf:"bytes,5,opt,name=contact_no,json=contactNo,proto3" json:"contact_no,omitempty"`
	CreatedBy            int32    `protobuf:"varint,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UserSource           string   `protobuf:"bytes,7,opt,name=user_source,json=userSource,proto3" json:"user_source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupRequest) Reset()         { *m = SignupRequest{} }
func (m *SignupRequest) String() string { return proto.CompactTextString(m) }
func (*SignupRequest) ProtoMessage()    {}
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{6}
}

func (m *SignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupRequest.Unmarshal(m, b)
}
func (m *SignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupRequest.Marshal(b, m, deterministic)
}
func (m *SignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupRequest.Merge(m, src)
}
func (m *SignupRequest) XXX_Size() int {
	return xxx_messageInfo_SignupRequest.Size(m)
}
func (m *SignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupRequest proto.InternalMessageInfo

func (m *SignupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SignupRequest) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *SignupRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *SignupRequest) GetContactNo() string {
	if m != nil {
		return m.ContactNo
	}
	return ""
}

func (m *SignupRequest) GetCreatedBy() int32 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func (m *SignupRequest) GetUserSource() string {
	if m != nil {
		return m.UserSource
	}
	return ""
}

type SignupReply struct {
	Data                 *SignUpReplyData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status               bool             `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string           `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error                string           `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SignupReply) Reset()         { *m = SignupReply{} }
func (m *SignupReply) String() string { return proto.CompactTextString(m) }
func (*SignupReply) ProtoMessage()    {}
func (*SignupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{7}
}

func (m *SignupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupReply.Unmarshal(m, b)
}
func (m *SignupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupReply.Marshal(b, m, deterministic)
}
func (m *SignupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupReply.Merge(m, src)
}
func (m *SignupReply) XXX_Size() int {
	return xxx_messageInfo_SignupReply.Size(m)
}
func (m *SignupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupReply.DiscardUnknown(m)
}

var xxx_messageInfo_SignupReply proto.InternalMessageInfo

func (m *SignupReply) GetData() *SignUpReplyData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SignupReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *SignupReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SignupReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type PhoneVerifyRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneVerifyRequest) Reset()         { *m = PhoneVerifyRequest{} }
func (m *PhoneVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*PhoneVerifyRequest) ProtoMessage()    {}
func (*PhoneVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{8}
}

func (m *PhoneVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneVerifyRequest.Unmarshal(m, b)
}
func (m *PhoneVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneVerifyRequest.Marshal(b, m, deterministic)
}
func (m *PhoneVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneVerifyRequest.Merge(m, src)
}
func (m *PhoneVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_PhoneVerifyRequest.Size(m)
}
func (m *PhoneVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneVerifyRequest proto.InternalMessageInfo

func (m *PhoneVerifyRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PhoneVerifyRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PhoneVerifyRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{9}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	Data                 *LoginReplyData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status               bool            `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string          `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error                string          `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{10}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetData() *LoginReplyData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LoginReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *LoginReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ForgotPasswordRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotPasswordRequest) Reset()         { *m = ForgotPasswordRequest{} }
func (m *ForgotPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordRequest) ProtoMessage()    {}
func (*ForgotPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{11}
}

func (m *ForgotPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordRequest.Unmarshal(m, b)
}
func (m *ForgotPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordRequest.Merge(m, src)
}
func (m *ForgotPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordRequest.Size(m)
}
func (m *ForgotPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordRequest proto.InternalMessageInfo

func (m *ForgotPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ForgotPasswordReply struct {
	Status               bool             `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error                string           `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Data                 *ForgotReplyData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ForgotPasswordReply) Reset()         { *m = ForgotPasswordReply{} }
func (m *ForgotPasswordReply) String() string { return proto.CompactTextString(m) }
func (*ForgotPasswordReply) ProtoMessage()    {}
func (*ForgotPasswordReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{12}
}

func (m *ForgotPasswordReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotPasswordReply.Unmarshal(m, b)
}
func (m *ForgotPasswordReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotPasswordReply.Marshal(b, m, deterministic)
}
func (m *ForgotPasswordReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotPasswordReply.Merge(m, src)
}
func (m *ForgotPasswordReply) XXX_Size() int {
	return xxx_messageInfo_ForgotPasswordReply.Size(m)
}
func (m *ForgotPasswordReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotPasswordReply.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotPasswordReply proto.InternalMessageInfo

func (m *ForgotPasswordReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *ForgotPasswordReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ForgotPasswordReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ForgotPasswordReply) GetData() *ForgotReplyData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ForgotReplyData struct {
	ResetPasswordToken   string   `protobuf:"bytes,1,opt,name=reset_password_token,json=resetPasswordToken,proto3" json:"reset_password_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForgotReplyData) Reset()         { *m = ForgotReplyData{} }
func (m *ForgotReplyData) String() string { return proto.CompactTextString(m) }
func (*ForgotReplyData) ProtoMessage()    {}
func (*ForgotReplyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{13}
}

func (m *ForgotReplyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForgotReplyData.Unmarshal(m, b)
}
func (m *ForgotReplyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForgotReplyData.Marshal(b, m, deterministic)
}
func (m *ForgotReplyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForgotReplyData.Merge(m, src)
}
func (m *ForgotReplyData) XXX_Size() int {
	return xxx_messageInfo_ForgotReplyData.Size(m)
}
func (m *ForgotReplyData) XXX_DiscardUnknown() {
	xxx_messageInfo_ForgotReplyData.DiscardUnknown(m)
}

var xxx_messageInfo_ForgotReplyData proto.InternalMessageInfo

func (m *ForgotReplyData) GetResetPasswordToken() string {
	if m != nil {
		return m.ResetPasswordToken
	}
	return ""
}

type LoginReplyData struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReplyData) Reset()         { *m = LoginReplyData{} }
func (m *LoginReplyData) String() string { return proto.CompactTextString(m) }
func (*LoginReplyData) ProtoMessage()    {}
func (*LoginReplyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{14}
}

func (m *LoginReplyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReplyData.Unmarshal(m, b)
}
func (m *LoginReplyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReplyData.Marshal(b, m, deterministic)
}
func (m *LoginReplyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReplyData.Merge(m, src)
}
func (m *LoginReplyData) XXX_Size() int {
	return xxx_messageInfo_LoginReplyData.Size(m)
}
func (m *LoginReplyData) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReplyData.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReplyData proto.InternalMessageInfo

func (m *LoginReplyData) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type SignUpReplyData struct {
	VerifyPhoneToken     string   `protobuf:"bytes,1,opt,name=verify_phone_token,json=verifyPhoneToken,proto3" json:"verify_phone_token,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId            int32    `protobuf:"varint,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpReplyData) Reset()         { *m = SignUpReplyData{} }
func (m *SignUpReplyData) String() string { return proto.CompactTextString(m) }
func (*SignUpReplyData) ProtoMessage()    {}
func (*SignUpReplyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{15}
}

func (m *SignUpReplyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpReplyData.Unmarshal(m, b)
}
func (m *SignUpReplyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpReplyData.Marshal(b, m, deterministic)
}
func (m *SignUpReplyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpReplyData.Merge(m, src)
}
func (m *SignUpReplyData) XXX_Size() int {
	return xxx_messageInfo_SignUpReplyData.Size(m)
}
func (m *SignUpReplyData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpReplyData.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpReplyData proto.InternalMessageInfo

func (m *SignUpReplyData) GetVerifyPhoneToken() string {
	if m != nil {
		return m.VerifyPhoneToken
	}
	return ""
}

func (m *SignUpReplyData) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SignUpReplyData) GetCompanyId() int32 {
	if m != nil {
		return m.CompanyId
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{16}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type CreateCompanyRequest struct {
	CompanyName          string   `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ContactNo            string   `protobuf:"bytes,3,opt,name=contact_no,json=contactNo,proto3" json:"contact_no,omitempty"`
	EmailAddress         string   `protobuf:"bytes,4,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	GstNo                string   `protobuf:"bytes,5,opt,name=gst_no,json=gstNo,proto3" json:"gst_no,omitempty"`
	GstNoFile            string   `protobuf:"bytes,6,opt,name=gst_no_file,json=gstNoFile,proto3" json:"gst_no_file,omitempty"`
	PanNo                string   `protobuf:"bytes,7,opt,name=pan_no,json=panNo,proto3" json:"pan_no,omitempty"`
	PanNoFile            string   `protobuf:"bytes,8,opt,name=pan_no_file,json=panNoFile,proto3" json:"pan_no_file,omitempty"`
	BankAccountNo        string   `protobuf:"bytes,9,opt,name=bank_account_no,json=bankAccountNo,proto3" json:"bank_account_no,omitempty"`
	CreatedBy            int32    `protobuf:"varint,10,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCompanyRequest) Reset()         { *m = CreateCompanyRequest{} }
func (m *CreateCompanyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCompanyRequest) ProtoMessage()    {}
func (*CreateCompanyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{17}
}

func (m *CreateCompanyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCompanyRequest.Unmarshal(m, b)
}
func (m *CreateCompanyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCompanyRequest.Marshal(b, m, deterministic)
}
func (m *CreateCompanyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCompanyRequest.Merge(m, src)
}
func (m *CreateCompanyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCompanyRequest.Size(m)
}
func (m *CreateCompanyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCompanyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCompanyRequest proto.InternalMessageInfo

func (m *CreateCompanyRequest) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func (m *CreateCompanyRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *CreateCompanyRequest) GetContactNo() string {
	if m != nil {
		return m.ContactNo
	}
	return ""
}

func (m *CreateCompanyRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *CreateCompanyRequest) GetGstNo() string {
	if m != nil {
		return m.GstNo
	}
	return ""
}

func (m *CreateCompanyRequest) GetGstNoFile() string {
	if m != nil {
		return m.GstNoFile
	}
	return ""
}

func (m *CreateCompanyRequest) GetPanNo() string {
	if m != nil {
		return m.PanNo
	}
	return ""
}

func (m *CreateCompanyRequest) GetPanNoFile() string {
	if m != nil {
		return m.PanNoFile
	}
	return ""
}

func (m *CreateCompanyRequest) GetBankAccountNo() string {
	if m != nil {
		return m.BankAccountNo
	}
	return ""
}

func (m *CreateCompanyRequest) GetCreatedBy() int32 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

type CreateCompanyReply struct {
	Data                 *CreateCompanyReplyData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status               bool                    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string                  `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error                string                  `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CreateCompanyReply) Reset()         { *m = CreateCompanyReply{} }
func (m *CreateCompanyReply) String() string { return proto.CompactTextString(m) }
func (*CreateCompanyReply) ProtoMessage()    {}
func (*CreateCompanyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{18}
}

func (m *CreateCompanyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCompanyReply.Unmarshal(m, b)
}
func (m *CreateCompanyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCompanyReply.Marshal(b, m, deterministic)
}
func (m *CreateCompanyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCompanyReply.Merge(m, src)
}
func (m *CreateCompanyReply) XXX_Size() int {
	return xxx_messageInfo_CreateCompanyReply.Size(m)
}
func (m *CreateCompanyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCompanyReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCompanyReply proto.InternalMessageInfo

func (m *CreateCompanyReply) GetData() *CreateCompanyReplyData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateCompanyReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *CreateCompanyReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateCompanyReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type CreateCompanyReplyData struct {
	CompanyId            int32    `protobuf:"varint,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCompanyReplyData) Reset()         { *m = CreateCompanyReplyData{} }
func (m *CreateCompanyReplyData) String() string { return proto.CompactTextString(m) }
func (*CreateCompanyReplyData) ProtoMessage()    {}
func (*CreateCompanyReplyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{19}
}

func (m *CreateCompanyReplyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCompanyReplyData.Unmarshal(m, b)
}
func (m *CreateCompanyReplyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCompanyReplyData.Marshal(b, m, deterministic)
}
func (m *CreateCompanyReplyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCompanyReplyData.Merge(m, src)
}
func (m *CreateCompanyReplyData) XXX_Size() int {
	return xxx_messageInfo_CreateCompanyReplyData.Size(m)
}
func (m *CreateCompanyReplyData) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCompanyReplyData.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCompanyReplyData proto.InternalMessageInfo

func (m *CreateCompanyReplyData) GetCompanyId() int32 {
	if m != nil {
		return m.CompanyId
	}
	return 0
}

type CreateCompanyUserRequest struct {
	CompanyId            int32    `protobuf:"varint,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedBy            int32    `protobuf:"varint,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCompanyUserRequest) Reset()         { *m = CreateCompanyUserRequest{} }
func (m *CreateCompanyUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCompanyUserRequest) ProtoMessage()    {}
func (*CreateCompanyUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f7b4a9246ff88, []int{20}
}

func (m *CreateCompanyUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCompanyUserRequest.Unmarshal(m, b)
}
func (m *CreateCompanyUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCompanyUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateCompanyUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCompanyUserRequest.Merge(m, src)
}
func (m *CreateCompanyUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCompanyUserRequest.Size(m)
}
func (m *CreateCompanyUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCompanyUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCompanyUserRequest proto.InternalMessageInfo

func (m *CreateCompanyUserRequest) GetCompanyId() int32 {
	if m != nil {
		return m.CompanyId
	}
	return 0
}

func (m *CreateCompanyUserRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateCompanyUserRequest) GetCreatedBy() int32 {
	if m != nil {
		return m.CreatedBy
	}
	return 0
}

func init() {
	proto.RegisterType((*EditUserRequest)(nil), "User.EditUserRequest")
	proto.RegisterType((*GenericReply)(nil), "User.GenericReply")
	proto.RegisterType((*ResendCodeRequest)(nil), "User.ResendCodeRequest")
	proto.RegisterType((*EmailVerifyRequest)(nil), "User.EmailVerifyRequest")
	proto.RegisterType((*OtpRequest)(nil), "User.OtpRequest")
	proto.RegisterType((*ResetPasswordRequest)(nil), "User.ResetPasswordRequest")
	proto.RegisterType((*SignupRequest)(nil), "User.SignupRequest")
	proto.RegisterType((*SignupReply)(nil), "User.SignupReply")
	proto.RegisterType((*PhoneVerifyRequest)(nil), "User.PhoneVerifyRequest")
	proto.RegisterType((*LoginRequest)(nil), "User.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "User.LoginReply")
	proto.RegisterType((*ForgotPasswordRequest)(nil), "User.ForgotPasswordRequest")
	proto.RegisterType((*ForgotPasswordReply)(nil), "User.ForgotPasswordReply")
	proto.RegisterType((*ForgotReplyData)(nil), "User.ForgotReplyData")
	proto.RegisterType((*LoginReplyData)(nil), "User.LoginReplyData")
	proto.RegisterType((*SignUpReplyData)(nil), "User.SignUpReplyData")
	proto.RegisterType((*Empty)(nil), "User.Empty")
	proto.RegisterType((*CreateCompanyRequest)(nil), "User.CreateCompanyRequest")
	proto.RegisterType((*CreateCompanyReply)(nil), "User.CreateCompanyReply")
	proto.RegisterType((*CreateCompanyReplyData)(nil), "User.CreateCompanyReplyData")
	proto.RegisterType((*CreateCompanyUserRequest)(nil), "User.CreateCompanyUserRequest")
}

func init() { proto.RegisterFile("api/athUser/v1/athUser.proto", fileDescriptor_402f7b4a9246ff88) }

var fileDescriptor_402f7b4a9246ff88 = []byte{
	// 1106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x4d, 0x6f, 0xdb, 0x46,
	0x13, 0x0e, 0xad, 0x4f, 0x8e, 0x3f, 0x64, 0xaf, 0x25, 0x87, 0x96, 0xfd, 0xe6, 0x4d, 0xb7, 0x40,
	0xe1, 0x14, 0x6d, 0x9c, 0x26, 0x87, 0x5e, 0x9b, 0xb8, 0x4e, 0x62, 0x24, 0x70, 0x0c, 0xc6, 0xc9,
	0x29, 0xa8, 0xb0, 0x16, 0xd7, 0x32, 0x11, 0x89, 0xbb, 0x21, 0x57, 0x4e, 0x79, 0x29, 0x8a, 0x9e,
	0x7a, 0x28, 0x7a, 0xe9, 0xdf, 0xea, 0xad, 0x7f, 0xa0, 0x87, 0xfe, 0x8c, 0x1e, 0x8a, 0x9d, 0x25,
	0x4d, 0x72, 0x25, 0xdb, 0x41, 0xd1, 0xdc, 0xb4, 0xf3, 0xc9, 0x79, 0xf6, 0x99, 0xd9, 0x11, 0x6c,
	0x33, 0x19, 0xee, 0x32, 0x75, 0xf6, 0x2a, 0xe1, 0xf1, 0xee, 0xf9, 0x57, 0xf9, 0xcf, 0xbb, 0x32,
	0x16, 0x4a, 0x90, 0xba, 0xfe, 0xdd, 0xdf, 0x1e, 0x09, 0x31, 0x1a, 0xf3, 0x5d, 0x34, 0x8d, 0x22,
	0xa1, 0x98, 0x0a, 0x45, 0x94, 0x18, 0x1b, 0xfa, 0xb7, 0x03, 0x9d, 0xfd, 0x20, 0x54, 0xda, 0xd4,
	0xe7, 0xef, 0xa6, 0x3c, 0x51, 0xa4, 0x0b, 0x0d, 0x3e, 0x61, 0xe1, 0xd8, 0x73, 0x6e, 0x3b, 0x3b,
	0xae, 0x6f, 0x0e, 0xe4, 0x13, 0x58, 0x1a, 0x8a, 0x89, 0x64, 0x51, 0x3a, 0x88, 0xd8, 0x84, 0x7b,
	0x0b, 0xa8, 0x5c, 0xcc, 0x64, 0x87, 0x6c, 0xc2, 0xc9, 0x16, 0xb8, 0xa7, 0xd3, 0xf1, 0xd8, 0xe8,
	0x6b, 0xa8, 0x6f, 0x6b, 0x01, 0x2a, 0xff, 0x07, 0x30, 0x14, 0x91, 0x62, 0x43, 0x35, 0x88, 0x84,
	0x57, 0x47, 0xad, 0x9b, 0x49, 0x0e, 0x85, 0x56, 0x4f, 0x65, 0xc0, 0x14, 0x0f, 0x06, 0x27, 0xa9,
	0xd7, 0xb8, 0xed, 0xec, 0x34, 0x7c, 0x37, 0x93, 0x3c, 0x4a, 0xc9, 0x4d, 0x68, 0x4d, 0x13, 0x1e,
	0x0f, 0xc2, 0xc0, 0x6b, 0xa2, 0xae, 0xa9, 0x8f, 0x07, 0x81, 0x09, 0x6b, 0x3e, 0x2b, 0x0c, 0xbc,
	0x96, 0xf1, 0xcb, 0x24, 0x46, 0x2d, 0x63, 0x71, 0x1a, 0x8e, 0xb9, 0x56, 0xb7, 0x8d, 0x3a, 0x93,
	0x1c, 0x04, 0xf4, 0x35, 0x2c, 0x3d, 0xe1, 0x11, 0x8f, 0xc3, 0xa1, 0xcf, 0xe5, 0x38, 0x25, 0x1b,
	0xd0, 0x4c, 0x14, 0x53, 0xd3, 0x04, 0x6b, 0x6f, 0xfb, 0xd9, 0x89, 0x78, 0xd0, 0x9a, 0xf0, 0x24,
	0x61, 0xa3, 0xbc, 0xee, 0xfc, 0x88, 0x60, 0xc5, 0xb1, 0x88, 0xb3, 0x7a, 0xcd, 0x81, 0x3e, 0x83,
	0x35, 0x9f, 0x27, 0x3c, 0x0a, 0xf6, 0x44, 0xc0, 0x73, 0x5c, 0xab, 0x08, 0x38, 0x36, 0x02, 0xa5,
	0x12, 0x17, 0xca, 0x25, 0xd2, 0xcf, 0x81, 0xec, 0xeb, 0x2b, 0x78, 0xcd, 0xe3, 0xf0, 0x34, 0xbd,
	0xf2, 0x96, 0xe8, 0x39, 0xc0, 0x0b, 0x25, 0x73, 0x9b, 0x1e, 0x34, 0x85, 0x92, 0x45, 0xb6, 0x86,
	0x50, 0xf2, 0x50, 0x90, 0x4d, 0x68, 0x6b, 0xb1, 0x4a, 0xe5, 0x45, 0x39, 0x42, 0xc9, 0xe3, 0x54,
	0xe2, 0x2d, 0x69, 0x15, 0xff, 0x5e, 0x86, 0x71, 0x8a, 0x35, 0x35, 0x7c, 0x57, 0x28, 0xb9, 0x8f,
	0x82, 0xf2, 0x37, 0xd6, 0x2b, 0xdf, 0xf8, 0x14, 0xba, 0xba, 0x60, 0x75, 0xc4, 0x92, 0xe4, 0xbd,
	0x88, 0x83, 0xab, 0xb9, 0xd4, 0x87, 0xb6, 0xcc, 0x0c, 0xb3, 0x0f, 0xb8, 0x38, 0xd3, 0x3f, 0x1d,
	0x58, 0x7e, 0x19, 0x8e, 0xa2, 0xa9, 0xfc, 0xd7, 0x31, 0x66, 0xb8, 0x5a, 0xbb, 0x86, 0xab, 0xf5,
	0x2b, 0xb9, 0xda, 0x98, 0xc3, 0xd5, 0x61, 0xcc, 0x73, 0xae, 0x36, 0x33, 0xce, 0x19, 0xc9, 0xa3,
	0x94, 0xfc, 0x1f, 0x16, 0x11, 0xa4, 0x44, 0x4c, 0xe3, 0x21, 0x47, 0x4e, 0xba, 0x3e, 0x68, 0xd1,
	0x4b, 0x94, 0xd0, 0x1f, 0x1d, 0x58, 0xcc, 0x4b, 0xd4, 0xac, 0xbb, 0x03, 0xf5, 0x80, 0x29, 0x86,
	0xf5, 0x2d, 0xde, 0xef, 0xdd, 0xc5, 0x1e, 0xd6, 0x06, 0xaf, 0x8c, 0xc1, 0xb7, 0x4c, 0x31, 0x1f,
	0x4d, 0x4a, 0x04, 0x5d, 0xb8, 0x8c, 0xa0, 0xb5, 0x4b, 0x08, 0x5a, 0x2f, 0x13, 0xd4, 0x07, 0x72,
	0x74, 0x26, 0x22, 0x5e, 0xe5, 0x14, 0x81, 0xfa, 0x50, 0x04, 0x3c, 0x03, 0x1a, 0x7f, 0x6b, 0x59,
	0x89, 0x28, 0xf8, 0xbb, 0xb8, 0x91, 0x5a, 0x99, 0x7b, 0xdf, 0xc0, 0xd2, 0x73, 0x31, 0x0a, 0xa3,
	0x0f, 0xbf, 0xb7, 0x9a, 0x75, 0xf7, 0x3f, 0x00, 0x64, 0x11, 0x34, 0x2c, 0x3b, 0x15, 0x58, 0xba,
	0x06, 0x96, 0x42, 0xff, 0x11, 0x50, 0xf9, 0x12, 0x7a, 0x8f, 0x45, 0x3c, 0x12, 0x1f, 0x46, 0x63,
	0xfa, 0xb3, 0x03, 0xeb, 0xb6, 0xfd, 0x7f, 0x38, 0x45, 0x2e, 0x78, 0x51, 0x2f, 0xf3, 0xc2, 0x24,
	0xb4, 0x10, 0xa0, 0x7b, 0xd0, 0xb1, 0x14, 0xe4, 0x1e, 0x74, 0x63, 0xdd, 0x92, 0x83, 0x1c, 0xde,
	0x81, 0x12, 0x6f, 0x79, 0x94, 0x95, 0x40, 0xe2, 0x72, 0xbb, 0x1e, 0x6b, 0x0d, 0xbd, 0x03, 0x2b,
	0x55, 0x78, 0xcb, 0xfd, 0x6e, 0xdc, 0xf2, 0x7e, 0x7f, 0x0f, 0x1d, 0x8b, 0xa0, 0xe4, 0x0b, 0x20,
	0xe7, 0xc8, 0xa6, 0x81, 0xd4, 0xcc, 0xaa, 0x64, 0x5b, 0x35, 0x1a, 0xa4, 0x1c, 0xe6, 0xba, 0x74,
	0xda, 0x59, 0x03, 0xbd, 0x66, 0x0d, 0x74, 0xda, 0x82, 0xc6, 0xfe, 0x44, 0xaa, 0x94, 0xfe, 0xbe,
	0x00, 0xdd, 0x3d, 0xec, 0xb9, 0x3d, 0xa3, 0xcc, 0xef, 0xca, 0x6e, 0x7e, 0x67, 0xb6, 0xf9, 0x3d,
	0x68, 0xb1, 0x20, 0x88, 0x79, 0x92, 0xe4, 0x17, 0x91, 0x1d, 0xad, 0xce, 0xaf, 0xd9, 0x9d, 0xff,
	0x29, 0x2c, 0xe3, 0xd5, 0x0f, 0x72, 0x77, 0x43, 0x9f, 0x25, 0x14, 0x3e, 0xcc, 0x62, 0xf4, 0xa0,
	0x39, 0x4a, 0x4a, 0x93, 0xa3, 0x31, 0x4a, 0xb4, 0xef, 0x2d, 0x58, 0x34, 0xe2, 0x81, 0x7e, 0x7c,
	0x70, 0x6c, 0xb8, 0xbe, 0x8b, 0xba, 0xc7, 0xe1, 0x98, 0x6b, 0x37, 0xc9, 0x22, 0xed, 0x66, 0x26,
	0x46, 0x43, 0xb2, 0xc8, 0xb8, 0x19, 0xb1, 0x71, 0x6b, 0x1b, 0x37, 0xd4, 0xa1, 0xdb, 0x67, 0xd0,
	0x39, 0x61, 0xd1, 0xdb, 0x01, 0x1b, 0x0e, 0xc5, 0x34, 0xc2, 0xb4, 0x2e, 0xda, 0x2c, 0x6b, 0xf1,
	0x43, 0x23, 0x9d, 0x19, 0x5a, 0x60, 0x0d, 0x2d, 0xfa, 0xab, 0x03, 0xc4, 0x82, 0x53, 0x53, 0xf9,
	0x5e, 0xa5, 0x07, 0xb7, 0x0d, 0x05, 0x67, 0xed, 0x3e, 0x42, 0x2f, 0x7e, 0x0d, 0x1b, 0xf3, 0xf3,
	0x58, 0x0c, 0x71, 0x6c, 0x86, 0xbc, 0x03, 0xaf, 0xe2, 0x58, 0x5e, 0x6d, 0xae, 0x76, 0xbd, 0x9a,
	0x94, 0x05, 0x78, 0x35, 0x0b, 0xbc, 0xfb, 0xbf, 0xb4, 0x00, 0x97, 0x2d, 0xf2, 0x1c, 0xc0, 0x0c,
	0x76, 0x3c, 0xad, 0x17, 0x93, 0xfc, 0xe2, 0x35, 0xeb, 0xaf, 0x55, 0x85, 0x72, 0x9c, 0xd2, 0x8d,
	0x9f, 0xfe, 0xf8, 0xeb, 0xb7, 0x85, 0x55, 0xba, 0xa2, 0x77, 0xb8, 0x92, 0xff, 0x1b, 0xe8, 0x94,
	0x86, 0x34, 0x8a, 0x3c, 0xe3, 0x3d, 0x3b, 0xbb, 0xfb, 0xc4, 0x68, 0xca, 0xeb, 0x0c, 0xdd, 0xc2,
	0xc0, 0x3d, 0xba, 0xae, 0x03, 0xdb, 0xa1, 0xde, 0x40, 0xa7, 0xb4, 0x56, 0x94, 0xa3, 0xcf, 0x6e,
	0x1b, 0xd7, 0x47, 0xb7, 0x43, 0x1d, 0x01, 0x14, 0x1b, 0x10, 0xb9, 0x69, 0xdc, 0x67, 0x76, 0xa2,
	0x6b, 0xd1, 0x28, 0xc5, 0x78, 0x0a, 0x2e, 0x4e, 0x27, 0x0c, 0x4f, 0x2a, 0xaf, 0x81, 0x89, 0xb5,
	0x6a, 0xbf, 0x10, 0xb4, 0x87, 0xa1, 0x3a, 0x74, 0x59, 0x87, 0x2a, 0x9c, 0x9f, 0x41, 0x3b, 0xdf,
	0x79, 0x49, 0x36, 0x55, 0xad, 0x1d, 0x78, 0x6e, 0xbd, 0x5d, 0x8c, 0xb6, 0x42, 0x97, 0xb0, 0xde,
	0x3c, 0xc0, 0x19, 0x90, 0xea, 0x1b, 0x80, 0xd2, 0xad, 0xf2, 0xb0, 0xb6, 0x5e, 0x93, 0xfe, 0xe6,
	0x7c, 0xa5, 0xce, 0xd1, 0xc7, 0x1c, 0x5d, 0x4a, 0x74, 0x8e, 0xaa, 0x01, 0xf9, 0xce, 0x2c, 0x95,
	0xd5, 0x44, 0xfd, 0x02, 0xd9, 0x99, 0x3c, 0xf3, 0x8a, 0xd8, 0xc4, 0x04, 0xeb, 0x74, 0x2d, 0x47,
	0xb7, 0x88, 0xff, 0x04, 0x96, 0x2b, 0x8d, 0x93, 0xc7, 0x9e, 0x37, 0x65, 0xfb, 0xde, 0x65, 0xa3,
	0x80, 0xde, 0x20, 0x07, 0xb0, 0x36, 0xd3, 0x81, 0xe4, 0xd6, 0x1c, 0x87, 0xeb, 0x10, 0xbf, 0x41,
	0x1e, 0x80, 0x6b, 0x3c, 0x5e, 0x1c, 0x1f, 0x91, 0xec, 0x82, 0x8b, 0x05, 0x77, 0xbe, 0xd3, 0x49,
	0x13, 0xff, 0xdb, 0x3c, 0xf8, 0x27, 0x00, 0x00, 0xff, 0xff, 0xba, 0x87, 0x19, 0xd0, 0x1f, 0x0d,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	SignupUser(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupReply, error)
	PhoneVerifyUser(ctx context.Context, in *PhoneVerifyRequest, opts ...grpc.CallOption) (*GenericReply, error)
	EmailVerifyUser(ctx context.Context, in *EmailVerifyRequest, opts ...grpc.CallOption) (*GenericReply, error)
	ResendCode(ctx context.Context, in *ResendCodeRequest, opts ...grpc.CallOption) (*SignupReply, error)
	LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	EditUser(ctx context.Context, in *EditUserRequest, opts ...grpc.CallOption) (*GenericReply, error)
	ForgotPasswordUser(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordReply, error)
	ResetPasswordUser(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*GenericReply, error)
	CreateCompany(ctx context.Context, in *CreateCompanyRequest, opts ...grpc.CallOption) (*CreateCompanyReply, error)
	CreateCompanyUser(ctx context.Context, in *CreateCompanyUserRequest, opts ...grpc.CallOption) (*GenericReply, error)
	CreateOTP(ctx context.Context, in *OtpRequest, opts ...grpc.CallOption) (*GenericReply, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) SignupUser(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupReply, error) {
	out := new(SignupReply)
	err := c.cc.Invoke(ctx, "/User.User/SignupUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) PhoneVerifyUser(ctx context.Context, in *PhoneVerifyRequest, opts ...grpc.CallOption) (*GenericReply, error) {
	out := new(GenericReply)
	err := c.cc.Invoke(ctx, "/User.User/PhoneVerifyUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) EmailVerifyUser(ctx context.Context, in *EmailVerifyRequest, opts ...grpc.CallOption) (*GenericReply, error) {
	out := new(GenericReply)
	err := c.cc.Invoke(ctx, "/User.User/EmailVerifyUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) ResendCode(ctx context.Context, in *ResendCodeRequest, opts ...grpc.CallOption) (*SignupReply, error) {
	out := new(SignupReply)
	err := c.cc.Invoke(ctx, "/User.User/ResendCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) LoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/User.User/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) EditUser(ctx context.Context, in *EditUserRequest, opts ...grpc.CallOption) (*GenericReply, error) {
	out := new(GenericReply)
	err := c.cc.Invoke(ctx, "/User.User/EditUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) ForgotPasswordUser(ctx context.Context, in *ForgotPasswordRequest, opts ...grpc.CallOption) (*ForgotPasswordReply, error) {
	out := new(ForgotPasswordReply)
	err := c.cc.Invoke(ctx, "/User.User/ForgotPasswordUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) ResetPasswordUser(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*GenericReply, error) {
	out := new(GenericReply)
	err := c.cc.Invoke(ctx, "/User.User/ResetPasswordUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CreateCompany(ctx context.Context, in *CreateCompanyRequest, opts ...grpc.CallOption) (*CreateCompanyReply, error) {
	out := new(CreateCompanyReply)
	err := c.cc.Invoke(ctx, "/User.User/CreateCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CreateCompanyUser(ctx context.Context, in *CreateCompanyUserRequest, opts ...grpc.CallOption) (*GenericReply, error) {
	out := new(GenericReply)
	err := c.cc.Invoke(ctx, "/User.User/CreateCompanyUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CreateOTP(ctx context.Context, in *OtpRequest, opts ...grpc.CallOption) (*GenericReply, error) {
	out := new(GenericReply)
	err := c.cc.Invoke(ctx, "/User.User/CreateOTP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	SignupUser(context.Context, *SignupRequest) (*SignupReply, error)
	PhoneVerifyUser(context.Context, *PhoneVerifyRequest) (*GenericReply, error)
	EmailVerifyUser(context.Context, *EmailVerifyRequest) (*GenericReply, error)
	ResendCode(context.Context, *ResendCodeRequest) (*SignupReply, error)
	LoginUser(context.Context, *LoginRequest) (*LoginReply, error)
	EditUser(context.Context, *EditUserRequest) (*GenericReply, error)
	ForgotPasswordUser(context.Context, *ForgotPasswordRequest) (*ForgotPasswordReply, error)
	ResetPasswordUser(context.Context, *ResetPasswordRequest) (*GenericReply, error)
	CreateCompany(context.Context, *CreateCompanyRequest) (*CreateCompanyReply, error)
	CreateCompanyUser(context.Context, *CreateCompanyUserRequest) (*GenericReply, error)
	CreateOTP(context.Context, *OtpRequest) (*GenericReply, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) SignupUser(ctx context.Context, req *SignupRequest) (*SignupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignupUser not implemented")
}
func (*UnimplementedUserServer) PhoneVerifyUser(ctx context.Context, req *PhoneVerifyRequest) (*GenericReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PhoneVerifyUser not implemented")
}
func (*UnimplementedUserServer) EmailVerifyUser(ctx context.Context, req *EmailVerifyRequest) (*GenericReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmailVerifyUser not implemented")
}
func (*UnimplementedUserServer) ResendCode(ctx context.Context, req *ResendCodeRequest) (*SignupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResendCode not implemented")
}
func (*UnimplementedUserServer) LoginUser(ctx context.Context, req *LoginRequest) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginUser not implemented")
}
func (*UnimplementedUserServer) EditUser(ctx context.Context, req *EditUserRequest) (*GenericReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditUser not implemented")
}
func (*UnimplementedUserServer) ForgotPasswordUser(ctx context.Context, req *ForgotPasswordRequest) (*ForgotPasswordReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForgotPasswordUser not implemented")
}
func (*UnimplementedUserServer) ResetPasswordUser(ctx context.Context, req *ResetPasswordRequest) (*GenericReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPasswordUser not implemented")
}
func (*UnimplementedUserServer) CreateCompany(ctx context.Context, req *CreateCompanyRequest) (*CreateCompanyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCompany not implemented")
}
func (*UnimplementedUserServer) CreateCompanyUser(ctx context.Context, req *CreateCompanyUserRequest) (*GenericReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCompanyUser not implemented")
}
func (*UnimplementedUserServer) CreateOTP(ctx context.Context, req *OtpRequest) (*GenericReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOTP not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_SignupUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SignupUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.User/SignupUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SignupUser(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_PhoneVerifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhoneVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).PhoneVerifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.User/PhoneVerifyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).PhoneVerifyUser(ctx, req.(*PhoneVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_EmailVerifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).EmailVerifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.User/EmailVerifyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).EmailVerifyUser(ctx, req.(*EmailVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_ResendCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).ResendCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.User/ResendCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).ResendCode(ctx, req.(*ResendCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.User/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).LoginUser(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_EditUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).EditUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.User/EditUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).EditUser(ctx, req.(*EditUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_ForgotPasswordUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgotPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).ForgotPasswordUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.User/ForgotPasswordUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).ForgotPasswordUser(ctx, req.(*ForgotPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_ResetPasswordUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).ResetPasswordUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.User/ResetPasswordUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).ResetPasswordUser(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CreateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.User/CreateCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateCompany(ctx, req.(*CreateCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CreateCompanyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompanyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateCompanyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.User/CreateCompanyUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateCompanyUser(ctx, req.(*CreateCompanyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CreateOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/User.User/CreateOTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateOTP(ctx, req.(*OtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "User.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignupUser",
			Handler:    _User_SignupUser_Handler,
		},
		{
			MethodName: "PhoneVerifyUser",
			Handler:    _User_PhoneVerifyUser_Handler,
		},
		{
			MethodName: "EmailVerifyUser",
			Handler:    _User_EmailVerifyUser_Handler,
		},
		{
			MethodName: "ResendCode",
			Handler:    _User_ResendCode_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _User_LoginUser_Handler,
		},
		{
			MethodName: "EditUser",
			Handler:    _User_EditUser_Handler,
		},
		{
			MethodName: "ForgotPasswordUser",
			Handler:    _User_ForgotPasswordUser_Handler,
		},
		{
			MethodName: "ResetPasswordUser",
			Handler:    _User_ResetPasswordUser_Handler,
		},
		{
			MethodName: "CreateCompany",
			Handler:    _User_CreateCompany_Handler,
		},
		{
			MethodName: "CreateCompanyUser",
			Handler:    _User_CreateCompanyUser_Handler,
		},
		{
			MethodName: "CreateOTP",
			Handler:    _User_CreateOTP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/athUser/v1/athUser.proto",
}
